### ISSUE TITLE
vehicle not known in simpla

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#12931] opened 2023-03-28 05:23 UTC
Add your issue description here.
Hello, when I run my simulation with simpla,an exception happended on vehicle not known error. I cannot find where is wrong, could you help me solve it?
*If possible, upload an example that shows your problem.*
An example could be found in the attachment.
**SUMO-version:**
SUMO 1.6 version
**operating system:**
Windows OS
[vehicle12not_known.zip](https://github.com/eclipse/sumo/files/11085628/vehicle12not_known.zip)

**Comment by m-kro** [comment] 2023-03-28 06:49
I cannot reproduce any error using either the development version or the release v.1.16... Could you maybe add some more information:

- the actual error message
- the simulation time when it happens

**Comment by thinker310** [comment] 2023-03-28 07:37
![image](https://user-images.githubusercontent.com/62609436/228162863-c829b60c-f92a-4940-a8ca-86f761de7445.png)
![image](https://user-images.githubusercontent.com/62609436/228163033-cbfae1ca-61a3-48d1-a8cf-d55589404f54.png)
OK, the error as shown in the pictures above

**Comment by thinker310** [comment] 2023-03-28 10:33
> I cannot reproduce any error using either the development version or the release v.1.16... Could you maybe add some more information:
> 
> * the actual error message
> * the simulation time when it happens

I solved it just now. A suggestion hope can be adopted:
1. In _platoonmanager.py, add diagonosis if pltID in platoon list
![image](https://user-images.githubusercontent.com/62609436/228208605-9f55d6f0-a8bb-4840-84a6-819a4eb60a62.png)
2. In error_commit.py, add diagnosis if vehicleID in vehicle list
![image](https://user-images.githubusercontent.com/62609436/228209313-4a827a81-017d-4bb5-beb4-18e906cb221e.png)

**Comment by thinker310** [comment] 2023-03-29 13:42
Ok, I will upload my log output.

**Comment by thinker310** [comment] 2023-04-04 08:25
I encountered the error as mentioned above again, the attachment include log information and the archives for reproducing it. I run the simulation with release 1.16 and nightly latest version, the error that vehicle not known always happens. 
![image](https://user-images.githubusercontent.com/62609436/229732515-714d35c8-77cb-4eb0-a421-c3c356f97fa4.png)
[Demand1.zip](https://github.com/eclipse/sumo/files/11146299/Demand1.zip)


> The changes you suggested would avoid the error but rather hide the actual problem: Why is the vehicle in question not removed from simpla when it should (on my side this happens without problems). As _removeArrived is called before most other actions of the time step, there should be no need to check for existing vehicles later.
> 
> @thinker310 Could you maybe upload the log output of simpla (just write the sumo output to a file)?

**Comment by m-kro** [comment] 2023-04-04 11:26
This scenario still does not fail on my side. Maybe I was not clear enough about it: Could you please provide the output generated by simpla? Such output like the following:
```
Vehicle '769' resets switch waiting time. (PVehicle)
Vehicle '790' resets switch waiting time. (PVehicle)
Vehicle '2725' resets switch waiting time. (PVehicle)
Vehicle '607' resets switch waiting time. (PVehicle)
610.5: leaderSpeed = 13.608655826884789
leaderDecel = 4.5
gap = 18.134742067486997
```

**Comment by thinker310** [comment] 2023-04-04 12:51
> ide the output generated by simpla
Ok, is there any methods to export simpla log output? I can not find related instructions in SUMO documentation.

**Comment by m-kro** [comment] 2023-04-04 14:02
It should be printed to the console. You can save it in Windows command line using the `> output.txt` syntax (e.g. see [this page](https://www.howtogeek.com/306682/how-to-save-the-command-prompts-output-to-a-text-file-in-windows/) for help).

**Comment by thinker310** [comment] 2023-04-04 15:32
[console_log_ubuntu.txt](https://github.com/eclipse/sumo/files/11150171/console_log_ubuntu.txt)
Ok, thank you. This is the log generated by simpla.

> It should be printed to the console. You can save it in Windows command line using the `> output.txt` syntax (e.g. see [this page](https://www.howtogeek.com/306682/how-to-save-the-command-prompts-output-to-a-text-file-in-windows/) for help).

**Comment by thinker310** [comment] 2023-04-05 12:46
By the way, I ran it on Windows OS and Ubuntu, but no error happends on Mac. It's very weird.

**Comment by m-kro** [comment] 2023-04-11 12:40
Unfortunately, I didn't see anything strange in your log file. Does the Mac system have a different configuration regarding SUMO or Python?

**Comment by m-kro** [comment] 2023-05-05 12:46
Please post here again if you find more about the reasons for this problem. Closing as we cannot replicate the problem for now.

**Closed by m-kro** 2023-05-05 12:46 UTC
Labels: question, c:simpla
