### ISSUE TITLE
Discussion on simulation results

### ISSUE THREAD

**Issue by taowang7** [eclipse/sumo#4939] opened 2018-12-18 03:33 UTC
We now use a realworld road condition data to control the —weights-prefix in randomTrips.py . an edge's road condition is 3 (means congestion) then it get a weights of 0.7 for example. Then we use the routes produced by randomTrips.py to simulating real incidents.   However. we do not know if it makes sense cause when we compare the edge speed in  outputdata with real world data , it doesn't match .  Be grateful to  any suggestions .

**Comment by namdre** [comment] 2018-12-18 07:20
duplicate of #4926

**Closed by namdre** 2018-12-18 07:20 UTC
Labels: question
