### ISSUE TITLE
Netconvert incorrectly recreating geometries from shapefiles

### ISSUE THREAD

**Issue by michaelSederlin** [eclipse/sumo#8604] opened 2021-05-07 20:28 UTC
Hi, 

Has there been a regression in how Netconvert handles shape files with the latest update? 
I created a small test case in Qgis to show the problem, but this also occurs on my larger road network. 
Previously (presumably using 1.8.0) using neconvert on the larger network was fine. 

![image](https://user-images.githubusercontent.com/37883908/117504536-e48d3200-af82-11eb-9af1-b3350b6dc1a3.png)

Netconvert settings:   
netconvert --shapefile-prefix MySimpleRoad --output testnet.net.xml --shapefile.from-id from_id --shapefile.to-id to_id --shapefile.speed speed --shapefile.laneNumber nlanes

The resulting network: 
![image](https://user-images.githubusercontent.com/37883908/117504624-0be3ff00-af83-11eb-8ba3-c3f9ab10b6d1.png)

The input shapefile projection given by gdalsrsinfo is: 
![image](https://user-images.githubusercontent.com/37883908/117504805-55cce500-af83-11eb-8da8-75a523821391.png)

When explicitly setting the netconvert projection with --proj using the output of gdalsrsinfo I get an error stating the nodes are at the same location. 

For my larger network the process succeeds but produces a strongly malformed network.

**Comment by namdre** [comment] 2021-05-08 04:13
This looks light it might be a duplicate of #6936.
Please try option **--shapefile.traditional-axis-mapping** and check if the problem goes away.

**Comment by michaelSederlin** [comment] 2021-05-08 06:50
That seems to have worked in recreating the geometry in SUMO. 
With these inputs. (using a network in WGS84)
```
netconvert \
	--shapefile-prefix <INPUT SHAPE FILE PREFIX> \
	--output-file <OUTPUT FILENAME> \
	--shapefile.to-id to_node \
	--shapefile.from-id from_node \
	--shapefile.laneNumber <LANE COUNT FIELD> \
	--shapefile.speed <SPEED FIELD> \
	--shapefile.traditional-axis-mapping
```
However I seem to have some dependency issues with proj.4 depending on which conda environment I am in when I do the netconvert so it's likely there is some problem on my end. 
But using a bash script with the same shapefile as before produces the strange results so maybe that is not the entire story.

Anyway, It appears that this solves the problem for me. Thank you for the quick response.

**Comment by namdre** [comment] 2021-05-10 07:28
The proj tools treat the axis order differently depending on their version.

**Closed by namdre** 2021-05-10 07:28 UTC
Labels: a:netconvert, duplicate, question
