### ISSUE TITLE
Error: Cannot get file attributes for osm-file

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#6620] opened 2020-02-09 13:19 UTC
Should be reproducible with:
[files](https://drive.google.com/drive/folders/1UtSM-PLMPPDLLq_7MssdzUaMwV2a4cGN?usp=sharing
)
SUMO Version v1_4_0+0978-a1a01cdbf1
LAX_raw.osm is a large OSM XML (sorry for the size - as always very large).

```
Loading configuration ... done.
Parsing types from 'standard.typ.xml' ... done.
Parsing nodes from osm-file 'LAX_planet.osm' ... 
Error: Cannot get file attributes for file 'LAX_planet.osm'!
Error: No nodes loaded.
Quitting (on error).
```

**Comment by namdre** [comment] 2020-02-09 16:02
Have you tried reproducing this with a smaller file?

**Comment by ambuehll** [comment] 2020-02-09 19:41
I double checked. It is true, with smaller files, netconvert does not crash. 
However, the same large file does **not** crash with 1.3 (I checked just now again). 
So, there seems to be something throwing 1.4 off. 
Thanks.

**Comment by ambuehll** [comment] 2020-11-11 12:51
for anyone else having this issue. A quick workaround: 
1. get osmfilter.exe 
2. run osmfilter.exe yourOSMfile.osm --keep="highway=" >newOSMfile.osm
3. run netconvert on newOSMfile.osm

This reduces the OSM file substantially by filtering only for tags with "highway". If you're using activitygen, it's another story, since you might want to keep other tags as well.

**Comment by namdre** [comment] 2020-11-12 06:57
Quite likely later versions of netconvert require more memory for the same file because they keep more internal state while parsing. Can you give a rough estimate of the file size threshold that makes 1.4 (or 1.7) crash?

**Comment by ambuehll** [comment] 2020-11-12 12:15
Somewhere between 3GB and 4GB. 3 still works, 4GB crashes.

**Comment by namdre** [comment] 2020-11-12 14:04
That sound suspiciously like a 32bit/64bit issue. I do recall importing networks with more than 4GB successfully though (on a machine with 96GB RAM).

**Comment by ambuehll** [comment] 2020-11-12 20:14
Currently runs on a Windows 2016 server, 256GB RAM, in 64bit.
Happy to run more tests, if you guide me.

**Comment by namdre** [comment] 2020-11-13 07:43
Try running it on a linux system to check whether the issue is platform dependent.

**Comment by ambuehll** [comment] 2020-11-14 16:11
ran it on macOS, same issue.

**Comment by namdre** [comment] 2020-11-16 06:54
the import worked fine on my linux box with 16GB RAM.

**Comment by behrisch** [comment] 2021-01-13 18:47
@ambuehll Can you please recheck with an up to date build (of tomorrow ;-)) whether the problem is fixed on Windows and report your MacOS version?

**Comment by ambuehll** [comment] 2021-01-14 21:32
yes, I confirm, this is fixed now on Windows! Thanks a lot. 
Lukas

**Comment by behrisch** [comment] 2021-01-15 07:48
We still need to test this for MacOS. @RobertHilbrich @angelobanse @ambuehll @schwamborn

**Comment by angelobanse** [comment] 2021-01-15 12:43
I don't get any error on macOS

**Closed** 2021-01-15 12:54 UTC
Labels: a:netconvert, bug

**Comment by schwamborn** [comment] 2021-01-15 13:13
Can confirm. No problem on macOS v11.1.
