### ISSUE TITLE
Problem on flexibility of GTFS import

### ISSUE THREAD

**Issue by Nigito** [eclipse/sumo#10033] opened 2022-01-24 15:17 UTC
It is currently complicated to define precise trajectories as well as the positioning of bus stops during GTFS import (gtfs2pt.py function). Indeed, the algorithm defines the shortest path to define the trajectory of the bus, implying an inconsistent positioning of the bus stops with respect to the coordinates defined in the GTFS file (stops.txt file).

How to define the stops from the "stops.txt" file and define the trajectories from the shapes ("shapes.txt")?
  
---
SUMO-version: 1.11.0
operating system: Windows 10 (64 bits)

**Comment by namdre** [comment] 2022-08-11 13:05
duplicate of #11327

**Closed by namdre** 2022-08-11 13:05 UTC
Labels: duplicate, question
