### ISSUE TITLE
Truck as Taxi with container stopped triggered at container stop

### ISSUE THREAD

**Issue by MelanieWeber** [eclipse/sumo#8386] opened 2021-03-18 11:50 UTC
![grafik](https://user-images.githubusercontent.com/38243649/111621213-015d8280-87e8-11eb-9872-232cb0eaf3bc.png)
Truck work as a container taxi. It work for the first 12 containers and then the truck stay at the containerstop instead of driving to the next one. The courent route change to "stopped triggered"

see the files.

**Comment by MelanieWeber** [comment] 2021-03-18 11:52
see timestep 26400 (and the next few seconds), Edge: -619741887, containerstop containerStop_-619741887_0

**Comment by namdre** [comment] 2021-03-18 14:49
It looks like the wrong files were packaged. The simulation gives
`Error: Unknown container stop 'containerStop_-gneE3_0' for container 'containerFlow_train0_Finntide'.`

**Comment by MelanieWeber** [comment] 2021-03-22 07:41
That's weird, I don't get an error when I run the simulation.

I use:
sumo-gui -n osm.rail.net.xml -r bug2.rou.xml -a stops_2.add.xml

Von: Jakob Erdmann ***@***.***>
Gesendet: Donnerstag, 18. März 2021 15:49
An: eclipse/sumo ***@***.***>
Cc: Weber, Melanie ***@***.***>; Author ***@***.***>
Betreff: Re: [eclipse/sumo] Truck as Taxi with container stopped triggered at container stop (#8386)


It looks like the wrong files were packaged. The simulation gives
Error: Unknown container stop 'containerStop_-gneE3_0' for container 'containerFlow_train0_Finntide'.

**Comment by namdre** [comment] 2021-03-22 07:49
mistake was on my end, sorry for that.

**Comment by namdre** [comment] 2021-03-22 08:50
problem is a duplicate of #7892. As a workaround you can set `personCapacity="1"` in vType type_truck_taxi

**Closed by namdre** 2021-03-22 08:50 UTC
Labels: a:sumo, bug, c:container, c:taxi

**Comment by namdre** [comment] 2021-03-22 08:54
also #8396 plays a role (containers were grouped and then not picked up due to capacity constraints).
