### ISSUE TITLE
allow retrieving of departed and arrived persons (trac #3247)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3247] opened 2017-06-29 06:05 UTC
traci.simulation.getDepartedPersonNumber
traci.simulation.getDepartedPersonIDList
...

Migrated from http://sumo.dlr.de/ticket/3247
```json
{
    "status": "new", 
    "changetime": "2017-06-29T06:05:20Z", 
    "description": "traci.simulation.getDepartedPersonNumber\ntraci.simulation.getDepartedPersonIDList\n...", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1498716320278222", 
    "component": "TraCI", 
    "summary": "allow retrieving of departed and arrived persons", 
    "priority": "major", 
    "keywords": "", 
    "time": "2017-06-29T06:05:20Z", 
    "milestone": "1.1.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by namdre** [comment] 2018-08-07 12:18
duplicate of #3477

**Closed by namdre** 2018-08-07 12:18 UTC
Labels: c:traci, enhancement
