### ISSUE TITLE
prefer end time of .config

### ISSUE THREAD

**Issue by rummel123** [eclipse/sumo#7833] opened 2020-11-20 11:46 UTC
I have a simulation with a defined start and end time in the .config file. Additionally I have route file with a person's depart time larger than this end time. The simulation runs until the person leaves the simulation. Test with vehicles gives the same behavior.

**Expected behavior:** Simulation ends at the defined end time of the .config file. All later departures are ignored.
[end_time_scenario.zip](https://github.com/eclipse/sumo/files/5573268/end_time_scenario.zip)

**Comment by rummel123** [comment] 2020-11-20 13:26
In this scenario I removed the trips with depart larger the end time. The scenario in running until all vehicles has left the simulation ignoring the end time. the scenario is running longer than the defined end time.
[end_time_scenario_small.zip](https://github.com/eclipse/sumo/files/5573737/end_time_scenario_small.zip)

**Comment by namdre** [comment] 2020-11-20 20:36
When I run this the scenario ends at step 1000. Please post the output of running 
`sumo -c test_scenario.sumocfg -v`

**Comment by rummel123** [comment] 2020-11-23 06:31
If I use command line with `sumo` or `sumo-gui` the simulation ends at step 1000. If use sumo-gui, the first time the simulation ends at step 1000. If I do **not** close sumo-gui and reload and run the scenario, the simulation ends at step 1228 with the information "All vehicles have left the simulation.". That is still the case until I close the window an restart sumo-gui.

**Comment by namdre** [comment] 2020-11-23 07:20
already fixed in dev version. duplicate of #7582

**Closed by namdre** 2020-11-23 07:20 UTC
Labels: a:sumo, bug
