### ISSUE TITLE
Sumo vehicle XY position not correct

### ISSUE THREAD

**Issue by lidongke** [eclipse/sumo#7707] opened 2020-10-22 07:50 UTC
I found that sumo vehicle's XY position that i get from SUMO-API not equal to SUMO-GUI the at the first step.The position in SUMO-GUI will less then SUMO-API.
For example:
at the first step: 
     position X: 510.73(with SUMO-GUI)
     position X: 512.825(with SUMO-API)
If i run next step ,they will be no different:
     position X: 511.883(with SUMO-GUI)
     position X: 511.883(with SUMO-API)
And the SL position looks like no problem.
How can i solve this?
@namdre 
@m-kro

**Comment by behrisch** [comment] 2020-10-25 13:36
Where exactly do you get the xy position from the GUI? whic sumo version do you use? By API you mean the python traci client?

**Comment by lidongke** [comment] 2020-10-26 10:57
I get xy position by mouse with sumo-gui.
I use the sumo master with 2020/9/16.
By API i mean TraCIAPI with c++.
@behrisch

**Comment by behrisch** [comment] 2020-10-26 15:15
Can you share your scenario?

**Comment by namdre** [comment] 2020-10-29 12:46
I think this is a duplicate of #1463

**Comment by behrisch** [comment] 2020-10-29 16:26
Maybe, but what is strange in this example is that the sumo-gui position increases while the other decreases. So this is at least not just an offset of one step in a regular vehicle movement.

**Comment by lidongke** [comment] 2020-10-31 07:51
In my opinion,I found that The position in SUMO-GUI will less then SUMO-API at the first simluation step,and they will be Basically equal at the second step(the xy position of SUMO-GUI will increase and the xy position of SUMO-API will reduce ).
How can i share my scenario to you?What data do you need?
@behrisch @namdre

**Comment by behrisch** [comment] 2020-10-31 16:31
The best thing is an example as small as possible showing the behavior. So a net file, a route file and a TraCI script (preferrably in python but you can also send your C++).

**Comment by namdre** [comment] 2021-04-12 07:54
closing for lack of feeeback

**Closed by namdre** 2021-04-12 07:54 UTC
Labels: question
