### ISSUE TITLE
add vehicle visualisation option for scaling lengths with length/geometry factor (trac #2892)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2892] opened 2017-02-24 09:56 UTC
Migrated from http://sumo.dlr.de/ticket/2892
```json
{
    "status": "new", 
    "changetime": "2017-02-24T09:56:28Z", 
    "description": "", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1487930188236842", 
    "component": "simulation gui (GUISIM)", 
    "summary": "add vehicle visualisation option for scaling lengths with lengt/geometry factor", 
    "priority": "major", 
    "keywords": "", 
    "time": "2017-02-24T09:56:28Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by namdre** [comment] 2021-10-01 08:11
duplicate of #6920

**Closed by namdre** 2021-10-01 08:11 UTC
Labels: duplicate, enhancement, a:sumo-gui
