### ISSUE TITLE
Libsumo on OSX causes segmentation fault

### ISSUE THREAD

**Issue by kanaadp** [eclipse/sumo#6804] opened 2020-03-15 00:41 UTC
Trying to build / use libsumo on macOS Catalina Version 10.15.3. Using latest SUMO build on github (36956f96df0d92337ae98977ae2d99a7180a8142). 

Build completes successfully, and other functionality seems to be working fine; however, importing libsumo fails with segmentation fault. This happens when the libsumo.py attempts to import _libsumo. Maybe an issue with SWIG on macOS? 

Versions for dependencies:
gdal 2.4.4_2
proj 7.0.0
swig 4.0.1

Thanks!

**Comment by schwamborn** [comment] 2020-03-16 13:33
The build you are referring to (36956f9) is from Sep 21, 2019, though. Is this a copy/paste error?

**Comment by schwamborn** [comment] 2020-04-01 12:16
Closing due to missing feedback.

**Comment by eugenevinitsky** [comment] 2020-08-06 19:07
I currently get the same segfault error after building off of 9a829a8a6a89929267fdc9725d8cdf5daf4e9455

>>> import libsumo
[1]    18008 segmentation fault  python

Any ideas?

**Comment by pikeas** [comment] 2020-11-03 22:57
I have the same issue. Libsumo immediately segfaults when building on a Mac (Sumo 1.7, macOS 10.15.7, Python 3.8.6).

**Comment by RobertHilbrich** [comment] 2020-11-05 19:19
Please make sure to use the same python version during build and for the `import libsumo` command. My macOS catalina still comes with python 2.7.16 and this is being used during compilation. It works fine with 2.7.16. However, using python3 (installed with brew and not selected during SUMO compilation) does not work. 
You will want to check your cmake configuration settings for SUMO to find out, which python version has been selected for compilation. Sometimes, brew updates python, so you may have to recompile ...

**Comment by pikeas** [comment] 2020-11-05 20:16
I built with Python 3.8.6 and attempted to use it with the same copy of Python.

@RobertHilbrich To clarify, you were able to use libsumo when built/run with Python 2.7, and saw a segfault when built/run with Python 3.x?

**Comment by RobertHilbrich** [comment] 2020-11-06 09:51
I was able to use libsumo when built/run with Python 2.7 on macOS Catalina; using python3 this lead to:
```
[robert:~/Git-Repositories] $ python3 
Python 3.8.2 (default, Sep 24 2020, 19:37:08) 
[Clang 12.0.0 (clang-1200.0.32.21)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import libsumo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/robert/Git-Repositories/SUMO/tools/libsumo/__init__.py", line 22, in <module>
    from .libsumo import vehicle, simulation, person, trafficlight
  File "/Users/robert/Git-Repositories/SUMO/tools/libsumo/libsumo.py", line 13, in <module>
    from . import _libsumo
ImportError: dynamic module does not define module export function (PyInit__libsumo)
```
While with python2:
```
[robert:~/Git-Repositories] $ python 

WARNING: Python 2.7 is not recommended. 
This version is included in macOS for compatibility with legacy software. 
Future versions of macOS will not include Python 2.7. 
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, Jun  5 2020, 22:59:21) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc- on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import libsumo
>>> 
```
And I set $PYTHONPATH to `/Users/robert/Git-Repositories/SUMO/tools` (where I cloned the head).

**Comment by RobertHilbrich** [comment] 2020-11-09 06:32
We spent some time to debug this issue on macOS Catalina this weekend. Turns out, there are usually three Python versions available on a mac with brew.
- Python 2.7 (shipped with macOS) - (`/usr/bin/python`)
- Python 3.8.2 (shipped with Xcode) - (`/usr/bin/python3`)
- Python 3.8.6 (installed with Brew) - (`/usr/local/bin/python3.8`)

If you do not configure anything "special" during `cmake`, it will find the Python 2.7 installation and use that version of the Python framework for building libsumo. In your cmake output, you will find something like this:
```
-- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
-- Found Python: /usr/bin/python
...
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found version "2.7.16") 
```
You should be able to just use python 2.7 and import libsumo.
```
Python 2.7.16 (default, Jun  5 2020, 22:59:21) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc- on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import libsumo
>>>
```

If you want to use Python 3.x, we recommend to use the Python 3.8.6 version shipped with Brew. (`brew install python@3.8`). In order to use this Python version, you have to tell CMake to use this particular Python interpreter:
```
cd $SUMO_HOME
mkdir -p out/build-python3.8
cd out/build-python3.8
cmake -DPYTHON_EXECUTABLE=/usr/local/bin/python3.8 ../..
```
In the CMake configuration output, you should see lines like the following:
```
-- Found PythonInterp: /usr/local/bin/python3.8 (found version "3.8.6")
... 
-- Found PythonLibs: /usr/local/Frameworks/Python.framework/Versions/3.8/lib/libpython3.8.dylib (found version "3.8.6") 
```
After building, you should be able to load `libsumo`
```
$ python3.8                                                                                                           
Python 3.8.6 (default, Oct 27 2020, 08:57:44) 
[Clang 12.0.0 (clang-1200.0.32.21)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import libsumo
>>> 
```

If you do not want to use Python 2.7 (from macOS) or Python 3.8.6 (from Brew), but instead Python 3.8.2 from Xcode, you will need to change the `CMakeCache.txt` in the build directory manually and point CMake to the direction of the PythonLibs for 3.8.2. On my mac, these are located here: `/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/`. However, please note, that we did not try this and cannot vouche for it. 

I think this should provide sufficient background and support to close this issue. Please report back, if this did not solve your issue.

**Closed** 2020-11-09 06:33 UTC
Labels: c:build, c:libsumo, mac

**Comment by pikeas** [comment] 2020-11-10 00:04
@RobertHilbrich Thanks for the extensive comment, it was extremely helpful!

I can confirm that `-DPYTHON_EXECUTABLE` builds an importable libsumo for homebrew managed `/usr/local/bin/python3.8`.

However, the same steps build a segfaulting libsumo when using any other (non-Homebrew, non-system) Python executable. Specifically, Pythons installed by asdf/pyenv.

```
$ wget -O - https://sumo.dlr.de/releases/1.7.0/sumo-src-1.7.0.tar.gz | tar xz
$ mkdir -p sumo-1.7.0/out/build-python3.8 &&  cd sumo-1.7.0/out/build-python3.8/
$ cmake -DPYTHON_EXECUTABLE=/Users/<me>/.asdf/installs/python/3.8.6/bin/python3.8 ../..
$ cmake --build . --parallel 10
$ PYTHONPATH=../../tools /Users/<me>/.asdf/installs/python/3.8.6/bin/python3.8 -c 'import libsumo'
fish: 'PYTHONPATH=../../tools /Users/p…' terminated by signal SIGSEGV (Address boundary error)
```

Sumo seems to be working when built against *and used by*Homebrew Python 3, however it would be great to be able to build against any Python 3!

**Comment by RobertHilbrich** [comment] 2020-11-10 09:11
Hm - in principle, it should work with any Python - even asdf Python. Could you check the CMakeCache.txt in out/build-python3.8 and make sure, that CMake found the .asdf-installation for the Python libraries? Maybe you could attach your CMakeCache.txt to this issue?

We have a similar situation with the XCode-version of Python 3.8. Even telling Cmake explicitly to use it (`cmake -DPYTHON_EXECUTABLE=/usr/bin/python3 ../..`), does not lead to the correct detection of the path of the Python libraries - instead it uses the libraries brew-Python, which results in a segfault.

**Comment by pikeas** [comment] 2020-11-10 17:16
In CMakeCache.txt, I see a few references to library paths that may be relevant:

```
PYTHON_INCLUDE_DIR:PATH=/usr/local/Frameworks/Python.framework/Versions/3.8/include/python3.8
PYTHON_LIBRARY:FILEPATH=/usr/local/Frameworks/Python.framework/Versions/3.8/lib/libpython3.8.dylib
FIND_PACKAGE_MESSAGE_DETAILS_PythonLibs:INTERNAL=[/usr/local/Frameworks/Python.framework/Versions/3.8/lib/libpython3.8.dylib][/usr/local/Frameworks/Python.framework/Versions/3.8/include/python3.8][v3.8.6()]
```

Full file: https://gist.github.com/pikeas/ce0e5167a863e98f217f11c404351121

**Comment by RobertHilbrich** [comment] 2020-11-11 06:48
This seems to be the exact problem. You told CMake to use the asdf Python interpreter (`cmake -DPYTHON_EXECUTABLE=/Users/<me>/.asdf/installs/python/3.8.6/bin/python3.8`) and I would assume, that your asdf Python installation is in `$HOME/.asdf`, but still CMake locate the Python 3.8 library in `/usr/local/Frameworks/Python.framework/Versions/3.8` - which probably refers to the brew installation. 

I think you should be able to locate the "include" and "lib" directory in your asdf installation in `$HOME/.asdf` and make the changes to the path settings in `CMakeCache.txt` manually. This should allow you to build a `libsumo` module which matches your asdf Python installation.

**Comment by schwamborn** [comment] 2020-11-11 12:45
Alternatively, specifying all three 
- `-DPYTHON_EXECUTABLE`
- `-DPYTHON_INCLUDE_DIR`
- `-DPYTHON_LIBRARY`

explicitly in the `cmake` call should also work.

**Comment by RobertHilbrich** [comment] 2020-11-11 15:33
Yes, I can confirm, that I could build against the default installation of Python3 (Xcode version) on macOS Catalina with the following `cmake` call:
```
cmake \
-DPYTHON_EXECUTABLE=/usr/bin/python3 \
-DPYTHON_INCLUDE_DIR:PATH=/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Headers \
-DPYTHON_LIBRARY:FILEPATH=/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/Current/lib/libpython3.8.dylib \
../..
```
Importing works fine:
```
python3
Python 3.8.2 (default, Sep 24 2020, 19:37:08) 
[Clang 12.0.0 (clang-1200.0.32.21)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import libsumo
>>> 
```
