### ISSUE TITLE
Leaving cursor over a button toggles multiple Tooltips at once

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#11278] opened 2022-08-03 10:26 UTC
It seems to only affect `sumo-gui` under macOS. It occurs when the cursor is left still over any button.

https://user-images.githubusercontent.com/16121932/182585511-e63ea534-e79c-4c0a-bfa2-037131f49df9.mov

OS: macOS Catalina (10.15.7)

**Comment by angelobanse** [comment] 2022-08-04 07:44
This also affects Linux
<img width="617" alt="Ubuntu" src="https://user-images.githubusercontent.com/16121932/182792251-2bccad1a-7e51-4d73-8cdf-7c18ec7a07ae.png">

OS: Ubuntu 18.04.6

**Comment by namdre** [comment] 2022-08-09 07:08
RHEL 7.9  
![grafik](https://user-images.githubusercontent.com/6240630/183586370-ce07d82a-6244-4fca-90cc-2e8688045153.png)

**Comment by namdre** [comment] 2022-08-26 11:07
If it cannot be fixed in a timely manner, I'd prefer the old no-tooltip behavior over releasing with this bug.

**Comment by palvarezlopez** [comment] 2022-08-26 11:13
Due the number of Mac-Users is very low, I can simply disable it only for MAC users. (I need just one code line)  @namdre @angelobanse what do you mean?

**Comment by angelobanse** [comment] 2022-08-26 11:31
I agree with Jakob, it is better to not have Tooltips (yet) than to have this bug. 

Pablo: Having OS-specific features (in this case Tooltips only on Windows) is not nice, keeping consistency is key!

**Comment by palvarezlopez** [comment] 2022-08-26 11:35
Ok, then I'm going to try the next week to solve the problem. If doesn't work, then disable it for all platforms

**Comment by namdre** [comment] 2022-08-26 12:51
Can still reproduce the problem

**Comment by angelobanse** [comment] 2022-08-29 09:20
It looks like it's already fixed

**Comment by namdre** [comment] 2022-08-29 10:19
found one more glitch.

**Comment by palvarezlopez** [comment] 2022-08-30 08:45
Problem is caused by MFXLCDLabel

**Comment by palvarezlopez** [comment] 2022-08-30 12:08
Fixed

**Closed by palvarezlopez** 2022-08-30 12:08 UTC
Labels: a:sumo-gui, linux, bug, mac, regression, FOX Modul
