### ISSUE TITLE
Crash between "g" light and "G" light

### ISSUE THREAD

**Issue by tomerkay** [eclipse/sumo#4029] opened 2018-05-01 21:23 UTC
Hello
During a simulation, I've noticed two vehicles crashed into each other inside the junction when one had a "G" light and the other had a "g" light.
Best regards,
Tomer Kay

**Comment by namdre** [comment] 2018-05-02 10:12
Thank you for reporting this. 
Can you attach the simulation scenario where this happend or send it to me privately?

**Comment by tomerkay** [comment] 2018-05-02 15:37
Thank you for answering!
Unfortunately I don't have the files of the simulation. I do have though a video that you can see it happening. I'll add it here. I spoke in Hebrew so I removed the audio. I explain there that the left car is going **straight** with "G" light, and the right car is going right with "g" light, then press "step" and they collide in the middle of the junction.
I hope It helps even though I don't have the files of the simulation itself.
Best,
Tomer
[collision_G_with_g.zip](https://github.com/eclipse/sumo/files/1967943/collision_G_with_g.zip)

**Comment by namdre** [comment] 2018-05-03 10:54
This could either be due to a bug in the net.xml file or a bug in the simulation logic. Without taking a look at the .net.xml I cannot tell the difference, sorry

**Comment by tomerkay** [comment] 2018-05-06 17:46
I have the net file! The accident occurred in junction is 37 during phase 6.
Thank you once again for the quick response!
[G_g_accident.net.zip](https://github.com/eclipse/sumo/files/1977856/G_g_accident.net.zip)

**Comment by namdre** [comment] 2018-05-07 05:56
Thanks. The error is in the traffic light plans, not in the simulation. Strangely, enough the network looks the same but has correct traffic light plans when I generate it on my end (using version 0.31.0 of netgenerate which was also used on your network).
I cannot reproduce the error with never versions of netgenerate either so I'm marking this as 'closed'. If you do figure out how this network came to be modified, please let me know.

**Closed by namdre** 2018-05-07 05:56 UTC

**Comment by tomerkay** [comment] 2018-05-07 06:26
We manually changed it while trying to improve our algorithm.😅
Still, Do you have an idea why the cars crashed? The phases suppose to be correct, am I wrong?
