### ISSUE TITLE
allow imgFile selection via a Dialog

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#8235] opened 2021-02-16 08:44 UTC
For the Polygon and POI `imgFile` attribute, it should be possible to click on the label (just as in `color`) and then in a Dialog navigate and select the desired image file.

**Comment by namdre** [comment] 2021-02-16 09:22
duplicate of #1627 (oldy bug oldy)

**Closed by namdre** 2021-02-16 09:22 UTC
Labels: a:netedit, duplicate, enhancement, netedit:additionalElements
