### ISSUE TITLE
The vehicle may turn left in the straight lane and right lanes

### ISSUE THREAD

**Issue by LuckyLeeLL** [eclipse/sumo#7116] opened 2020-06-05 02:14 UTC
Sumo is a small and refined software, it brings me a lot of convenience.
However,when i used  randomTrips.py ，something strange happened.

**The vehicle may turn left in the straight lane and right lanes**, which makes it impossible for me to control it through Traci. 

The command line is: 
/tools/randomTrips.py -n sumo_3.net.xml  -e 86400  --remove-loops --additional-file type.add.xml  -p 4 --fringe-factor=100 - -validate 

Sorry to bother you，but it really a trouble for me .

**Comment by LuckyLeeLL** [comment] 2020-06-05 03:37
<img width="425" alt="bug" src="https://user-images.githubusercontent.com/48266412/83834393-d0143a00-a720-11ea-8b3b-e87699a91e44.png">
as the picture show

**Comment by LuckyLeeLL** [comment] 2020-06-05 03:38
<img width="425" alt="bug" src="https://user-images.githubusercontent.com/48266412/83834439-eb7f4500-a720-11ea-94e9-6d258e06f4f4.png">
as the picture shows 
@namdre

**Comment by namdre** [comment] 2020-06-05 05:24
This has nothing to do with randomTrips but rather with the way the network is defined. Can you attach the network file (zipped)?

**Comment by LuckyLeeLL** [comment] 2020-06-05 06:54
> This has nothing to do with randomTrips but rather with the way the network is defined. Can you attach the network file (zipped)?

Thank you very much for your reply. This is my network file. I will check it again

[sumo_3_net.zip](https://github.com/eclipse/sumo/files/4734378/sumo_3_net.zip)

**Comment by namdre** [comment] 2020-06-05 07:29
The network connections are fine. However, the edges are very short and this means some vehicles do not manage to change to the appropriate turning lane in time. In the screenshot you are seeing a vehicle that wants to change to the left lane and then turn.
You can check this by 
- writing down the time and vehicle id
- re-running the simulation to a time ~20s earlier
- observing the same vehicle
See also https://sumo.dlr.de/docs/SUMO-GUI.html#showing_routes_and_route-related_information

Occasionally, the observed problem may occur because a vehicle has been inserted on the wrong lane. This can be fixed by adding the randomTrips option `--trip-attributes "departLane=\"best\""`

**Closed by namdre** 2020-06-05 07:29 UTC

**Comment by LuckyLeeLL** [comment] 2020-06-05 07:35
> The network connections are fine. However, the edges are very short and this means some vehicles do not manage to change to the appropriate turning lane in time. In the screenshot you are seeing a vehicle that wants to change to the left lane and then turn.
> You can check this by
> 
>     * writing down the time and vehicle id
> 
>     * re-running the simulation to a time ~20s earlier
> 
>     * observing the same vehicle
>       See also https://sumo.dlr.de/docs/SUMO-GUI.html#showing_routes_and_route-related_information
> 
> 
> Occasionally, the observed problem may occur because a vehicle has been inserted on the wrong lane. This can be fixed by adding the randomTrips option `--trip-attributes "departLane=\"best\""`

thank you very much , i will try again

**Comment by LuckyLeeLL** [comment] 2020-06-06 08:52
sorry,I would like to ask another question， i used `traci.lane.getCO2Emission(lanes)` get co2 emission , however , the obtained values are all 0.

the result as the picture show 
<img width="317" alt="co2" src="https://user-images.githubusercontent.com/48266412/83940267-f2d44a80-a815-11ea-8dfa-2f89b1e59bd9.png">

The route command line is:
`/tools/randomTrips.py -n sumo_3.net.xml -e 86400 --remove-loops --additional-file type.add.xml -p 4 --fringe-factor=100 - -validate --trip-attributes"departLane=\"best\""`
 @namdre

**Comment by namdre** [comment] 2020-06-07 11:20
Please post unrelated issues in another ticket and provide input files for reproducing.
