### ISSUE TITLE
Wrong answer received for add route command

### ISSUE THREAD

**Issue by Ildemselcuk** [eclipse/sumo#8173] opened 2021-02-01 20:29 UTC
It occurs when generating routes and vehicles at uncertain times. I usually get this error on the sumo-web 3d platform for more than one vehicle consecutively. I do not get such an error in Sumo simulation. I use latest sumo version.

```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ilyas/Desktop/GOHM/Repository/nga_itms_backend/sumo-web3d/sumo_web3d/server/server.py", line 700, in messagehandler
    defineVehicle(count,receive_message)
  File "/home/ilyas/Desktop/GOHM/Repository/nga_itms_backend/sumo-web3d/sumo_web3d/server/server.py", line 638, in defineVehicle
    addRoute(str(receive_message['route_name']),receive_message['target'])
  File "/home/ilyas/Desktop/GOHM/Repository/nga_itms_backend/sumo-web3d/sumo_web3d/server/server.py", line 619, in addRoute
    traci.route.add(routeID=route_name,edges=fromRoadsTo)
  File "/usr/share/sumo/tools/traci/_route.py", line 43, in add
    self._setCmd(tc.ADD, routeID, "l", edges)
  File "/usr/share/sumo/tools/traci/domain.py", line 185, in _setCmd
    self._connection._sendCmd(self._cmdSetID, varID, objectID, format, *values)
  File "/usr/share/sumo/tools/traci/connection.py", line 181, in _sendCmd
    return self._sendExact()
  File "/usr/share/sumo/tools/traci/connection.py", line 100, in _sendExact
    raise FatalTraCIError("Received answer %s for command %s." % (prefix[1], command))
traci.exceptions.FatalTraCIError: Received answer 180 for command 198.
```

**Comment by behrisch** [comment] 2021-02-02 07:58
Please check which SUMO version you are using and did you ask the [web3d people](https://github.com/sidewalklabs/sumo-web3d) as well?

**Comment by behrisch** [comment] 2021-02-02 09:06
maybe duplicate of #8174 ?

**Comment by namdre** [comment] 2021-04-12 07:53
at least strongly related to #8174

**Closed by namdre** 2021-04-12 07:53 UTC
Labels: duplicate, question
