### ISSUE TITLE
psv osm import backward and forwar

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#9519] opened 2021-11-10 19:08 UTC
Hi, 

An enhancement related to #6767 and #8317

`lanes:psv:backward` (or forward) does not get imported.
Would be great to import this as well. 

Thanks
Lukas

**Comment by namdre** [comment] 2021-11-10 19:25
This looks like a duplicate of #6767 or am I missing something?

**Comment by ambuehll** [comment] 2021-11-10 19:44
Back then it was about implementing psv which #8317 took care this year - partially.
What's missing is the forward/backward implementation from #6767. 
But, I guess you're right, it's a bit of a duplicate. Sorry 👍

**Comment by namdre** [comment] 2021-11-10 20:08
no problem. Serves as a reminder that #6767 is still relevant!

**Closed by namdre** 2021-11-10 20:08 UTC
Labels: duplicate
