### ISSUE TITLE
Could not simulate traffic using flowrouter.py

### ISSUE THREAD

**Issue by Thilaga22** [eclipse/sumo#11598] opened 2022-09-15 05:27 UTC
**Trouble creating traffic scenario using flowrouter.**

I am using sumo version 1.12.0, Windows 10 operating system.

I am trying to simulate the traffic scenario using flowrouter.py
Here is what i have done:

**Step1**
I downloaded required input files from Github https://github.com/eclipse/sumo/tree/main/tests/tools/detector/flowrouter/bell_pfe
Downloaded input files are below:
1) input_detectors.det.xml
2) input_flows.txt
3) input_net.net.xml
From Sumo\tools\detector. 
I moved flowrouter.py python coding into the local folder where the input files are saved. 

**Step2**
In the command prompt, i executed the below command,
D:\inputfolder>flowrouter.py -n input_net.net.xml -d input_detectors.det.xml -f input_flows.txt -o routes.xml -e flows.xml -i 60

**Issue:**
After executing the command, i get the below error. 

Traceback (most recent call last):
  File "D:\NICT\MM2ITS2\Plugins\SumoCoSimulation\Content\Python\flowrouter_github\flowrouter.py", line 989, in <module>
    sources, sinks = reader.readDetectors(options.detfile)
  File "D:\NICT\MM2ITS2\Plugins\SumoCoSimulation\Content\Python\flowrouter_github\flowrouter.py", line 845, in readDetectors
    self._detReader = detector.DetectorReader(detFile, self._lane2edge)
AttributeError: module 'detector' has no attribute 'DetectorReader'

![image](https://user-images.githubusercontent.com/85918822/190320728-bf73c4e9-cc82-4301-af7f-fd4dd85407c3.png)

It would be really helpful, if anyone could guide where I am wrong or what I am missing. 

Thanks in Advance,
Thilaga.

**Comment by namdre** [comment] 2022-09-15 06:53
flowrouter.py imports files relative to it's own module location. Moving it to another folder is likely the cause of your problem.
Instead call, it with its absolute path (d:\whatever\path\to\flowrouter.py arg1 arg2 ...).
See also https://sumo.dlr.de/docs/Demand/Routes_from_Observation_Points.html#chosing_the_right_tool

**Closed by namdre** 2022-09-15 06:53 UTC
Labels: question
