### ISSUE TITLE
dispatchTaxi() sometimes generates non-continuous routes

### ISSUE THREAD

**Issue by ArmelliniMG** [eclipse/sumo#8424] opened 2021-03-25 15:50 UTC
Sometimes when a new route is defined using dispatchTaxi(), the new route given to the vehicle consists of the current edge and the edge of the next stop and does not have the mid-edges. This causes the vehicle to be teleported.

Test scenario:
[test_routing.zip](https://github.com/eclipse/sumo/files/6206003/test_routing.zip)

**Comment by namdre** [comment] 2021-03-25 21:36
duplicate of #8423 (what a coincidence!)

**Closed by namdre** 2021-03-25 21:36 UTC
Labels: a:sumo, c:taxi, c:traci
