### ISSUE TITLE
Passengers cannot ride the subway

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#6885] opened 2020-04-13 12:08 UTC
Hello, I tried to build a multi-mode combined travel, and found two problems: 
1. Pedestrians can walk to the subway station and wait, but when the subway arrives at the station and stops for a period of time, the passengers still don’t get on the subway (the direction and station are correct).
![problem](https://user-images.githubusercontent.com/55737075/79119211-5fa50880-7dc2-11ea-8177-129c34f36025.png)
![still waiting](https://user-images.githubusercontent.com/55737075/79119219-66338000-7dc2-11ea-8bb8-19863213e6db.png)

2. I use osm data to import subway stations. Many stations are lost. I tried to use netedit to manually add stations. Whether passengers cannot find the way to the station without access lane.
![error](https://user-images.githubusercontent.com/55737075/79119247-76e3f600-7dc2-11ea-87b4-664e144a0020.png)

**Comment by namdre** [comment] 2020-04-13 13:30
1) Make sure that the 'lines' attribute of the ride matches or includes (it can be a list of values) the line attribute of the subway vehicle.
2) Add access definitions to connect the subway stations to the pedestrian part of the network in Netedit or use netconvert to automatically generate railway access by processing the stop file using options **--ptstop-files** and **--ptstop-output**

**Comment by Shiyunyang-seu** [comment] 2020-04-15 09:23
Hi, I add the access lane of subway, and the person walks to the station successfully. But he is always waiting there and do not get on the subway
![trip](https://user-images.githubusercontent.com/55737075/79321257-a3704d00-7f3d-11ea-835d-8a0b56851910.png)
![person plan](https://user-images.githubusercontent.com/55737075/79321361-cbf84700-7f3d-11ea-9524-5f42244bcbe0.png)

.

**Comment by namdre** [comment] 2020-04-15 09:43
the lines attribute of the person must match the 'id' attribute or the 'line' attribute of the vehicle to be used. The route id is irrelevant. You are not setting 'line' (see https://sumo.dlr.de/docs/IntermodalRouting.html#defining_public_transport).

**Comment by Shiyunyang-seu** [comment] 2020-04-15 12:53
Hi, I am so sorry to reopen this question again.When I make the person get off at the subway station and walk to his destination. The person cannot find the way from the subway station to the lane. But I have added the access lane to the subway 
![stop](https://user-images.githubusercontent.com/55737075/79339224-2227b300-7f5b-11ea-8d96-40e9dbe33e3d.png)
![erroe](https://user-images.githubusercontent.com/55737075/79339227-2358e000-7f5b-11ea-8277-f87bd2df4fad.png)

station.

**Comment by namdre** [comment] 2020-04-15 13:14
please zip and attach all input files to reproduce this.

**Comment by Shiyunyang-seu** [comment] 2020-04-15 13:23
[sumo-0415.zip](https://github.com/eclipse/sumo/files/4481403/sumo-0415.zip)

**Comment by namdre** [comment] 2020-04-16 07:30
caused by #2811

**Comment by namdre** [comment] 2020-04-16 08:49
fixed in [33f6af710dedadc1fabc050c9ed557cd34a8d1de]

**Closed by namdre** 2020-04-16 08:49 UTC
Labels: a:SUMO, bug, c:intermodal, question

**Comment by Shiyunyang-seu** [comment] 2020-04-16 12:13
Thank you for your helping. Should I download the updated version tonight to use the fixe the problem?




| |
史云阳
|
|
邮箱：15250989157@163.com
|

签名由 网易邮箱大师 定制

On 04/16/2020 16:49, Jakob Erdmann wrote:

Closed #6885.

**Comment by Shiyunyang-seu** [comment] 2020-04-16 13:29
Thanks for your helping! Should I download the updated version tonight to solve the problem?

**Comment by namdre** [comment] 2020-04-16 14:38
The download should be updated by April 17 2020 01:00:00 UTC. You can check the timestamp on the download page to see from which day the build is.
