### ISSUE TITLE
Problem of duaiterate.py and one-shot.py in sumo

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7603] opened 2020-09-26 09:51 UTC
Hi,there are some problems when I using sumo to solve the traffic assignment problem. Both duaiterate and one shot were adopted：
(1) When using duaiterate for allocation, the code is as follows:
![issues](https://user-images.githubusercontent.com/55737075/94337709-33eba700-001f-11eb-9eb3-7815d35d4bc7.png)
In addition to the road network file, the input file also contains the path file（ osm.rou.xml ）The route file is generated by duarouter. The first allocation can be performed normally by using duaiterate, but an error occurs in the second allocation
![dualterate](https://user-images.githubusercontent.com/55737075/94337678-fab33700-001e-11eb-9b19-4cfc83cd2d24.png)
The error indicates that there are illegal characters (line 54, column 307 ) in the output file in the last iteration 'osm_000.rou.atl.xml', but I found that there are no characters in column 307 of line 54.
![issue2](https://user-images.githubusercontent.com/55737075/94337793-ca1fcd00-001f-11eb-991c-9b84afaa8807.png)
(2) When using one-shot :
![one-shot](https://user-images.githubusercontent.com/55737075/94337816-f63b4e00-001f-11eb-9e75-982145974564.png)
![one-shot2](https://user-images.githubusercontent.com/55737075/94337819-f9ced500-001f-11eb-962a-03cb911e5ac2.png)
a certain vehicle has no effective path. When duaiterate is used, route files are generated by duarouter. If there is no valid path, "ignore errors" should be omitted.
(3)Another problem:
The input of duaiterate is net and trip, but I found that after entering net and trip, it will show that there is no definition for passenger. Even if Vtype is added, it is not successful.Therefore, I adjust the input file to network and route (in this case, the problem mentioned earlier appears). When I want to input net trip and route at the same time, there is an error saying that trip or route is not input (the error is, at least enter either of route trip or flow)
Thanks in advance!
[inputfile.zip](https://github.com/eclipse/sumo/files/5286480/inputfile.zip)

**Comment by namdre** [comment] 2020-10-07 09:31
1) possibly duplicate of #7621. Please check whether this solved your issue
2) od2trips does not guarantee valid trips. You may filter the trips using `duarouter -n net.net.xml -r trips.xml --write-trips validated.trips.xml --ignore-errors
3) you may pass additional files (i.e. with vTypes) in duaiterate by setting option **--additional**

**Closed by namdre** 2020-10-07 09:31 UTC
