### ISSUE TITLE
collision in sublane model when lane changing on separate internal edges (trac #3273)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3273] opened 2017-07-04 14:51 UTC
this was triggered by #2082 but could have caused problems before as well (at least when detecting overlap on the intersection itself).

Migrated from http://sumo.dlr.de/ticket/3273
```json
{
    "status": "new", 
    "changetime": "2017-07-04T14:51:54Z", 
    "description": "this was triggered by #2082 but could have caused problems before as well (at least when detecting overlap on the intersection itself).", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1499179914988027", 
    "component": "simulation general (micro)", 
    "summary": "collision in sublane model when lane changing on separate internal edges", 
    "priority": "major", 
    "keywords": "", 
    "time": "2017-07-04T14:51:54Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment] 2018-12-17 15:23
duplicate of #3619

**Closed by namdre** 2018-12-17 15:23 UTC
Labels: a:SUMO, bug, c:sublane
