### ISSUE TITLE
add possibility to record and replay traci communication

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#4658] opened 2018-10-02 21:36 UTC
this would help in sending bug reports without the need to send and run the actual scripts.

**Comment by namdre** [comment] 2020-08-27 12:39
duplicate of #6604

**Comment by namdre** [comment] 2020-08-27 12:40
it might still be useful to record the binary protocol but the current playback functionality has proven useful for the task.

**Closed by namdre** 2020-08-27 12:39 UTC
Labels: c:traci, duplicate
