### ISSUE TITLE
TraCI: How to debug: FatalTraCIError: connection closed by SUMO

### ISSUE THREAD

**Issue by philippwulff** [eclipse/sumo#8477] opened 2021-04-12 09:39 UTC
I have built a Python script around a SUMO simulation which periodically restarts the simulation and then increments the simulation time using a `step()` method. This method also calls the TraCI command `connection.simulation.simulationStep()`. However, sometimes it raises the exception below? Why does it happen and how could I debug it? 
What is `result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)`? I have a bunch of subscriptions to vehicles and other simulation variables. Does one of them cause this?

The error message appears in different situations, but the error message is always the same. I get this error sometimes in my code and mostly avoid it using `try: ... except FatalTraCIError: ...`, but that does not work here.

```
---------------------------------------------------------------------------
FatalTraCIError                           Traceback (most recent call last)
<ipython-input-4-a7449b31bcaf> in <module>
----> 1 agent.learn(100000)

~/anaconda3/envs/sumo_rl/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    278     ) -> "PPO":
    279 
--> 280         return super(PPO, self).learn(
    281             total_timesteps=total_timesteps,
    282             callback=callback,

~/anaconda3/envs/sumo_rl/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    225         while self.num_timesteps < total_timesteps:
    226 
--> 227             continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
    228 
    229             if continue_training is False:

~/anaconda3/envs/sumo_rl/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py in collect_rollouts(self, env, callback, rollout_buffer, n_rollout_steps)
    166                 clipped_actions = np.clip(actions, self.action_space.low, self.action_space.high)
    167 
--> 168             new_obs, rewards, dones, infos = env.step(clipped_actions)
    169 
    170             self.num_timesteps += env.num_envs

~/anaconda3/envs/sumo_rl/lib/python3.8/site-packages/stable_baselines3/common/vec_env/base_vec_env.py in step(self, actions)
    161         """
    162         self.step_async(actions)
--> 163         return self.step_wait()
    164 
    165     def get_images(self) -> Sequence[np.ndarray]:

~/anaconda3/envs/sumo_rl/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py in step_wait(self)
     41     def step_wait(self) -> VecEnvStepReturn:
     42         for env_idx in range(self.num_envs):
---> 43             obs, self.buf_rews[env_idx], self.buf_dones[env_idx], self.buf_infos[env_idx] = self.envs[env_idx].step(
     44                 self.actions[env_idx]
     45             )

~/anaconda3/envs/sumo_rl/lib/python3.8/site-packages/stable_baselines3/common/monitor.py in step(self, action)
     95         if self.needs_reset:
     96             raise RuntimeError("Tried to step environment that needs reset")
---> 97         observation, reward, done, info = self.env.step(action)
     98         self.rewards.append(reward)
     99         if done:

~/Code/ba_pw/sumo_rl/envs/env.py in step(self, rl_actions)
     42         self.apply_rl_actions(rl_actions_clipped)
     43 
---> 44         self.k.simulation.simulation_step()
     45         self.k.update()
     46 

~/Code/ba_pw/sumo_rl/kernel/simulation_kernel.py in simulation_step(self)
     84     def simulation_step(self):
     85         """Increment the simulation."""
---> 86         self.traci_api.simulationStep()
     87 
     88     def update(self):

~/anaconda3/envs/sumo_rl/lib/python3.8/site-packages/traci/connection.py in simulationStep(self, step)
    300         if type(step) is int and step >= 1000:
    301             warnings.warn("API change now handles step as floating point seconds", stacklevel=2)
--> 302         result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)
    303         for subscriptionResults in self._subscriptionMapping.values():
    304             subscriptionResults.reset()

~/anaconda3/envs/sumo_rl/lib/python3.8/site-packages/traci/connection.py in _sendCmd(self, cmdID, varID, objID, format, *values)
    178             self._string += struct.pack("!i", len(objID)) + objID.encode("latin1")
    179         self._string += packed
--> 180         return self._sendExact()
    181 
    182     def _readSubscription(self, result):

~/anaconda3/envs/sumo_rl/lib/python3.8/site-packages/traci/connection.py in _sendExact(self)
     88             self._socket.close()
     89             del self._socket
---> 90             raise FatalTraCIError("connection closed by SUMO")
     91         for command in self._queue:
     92             prefix = result.read("!BBB")

FatalTraCIError: connection closed by SUMO
```

**Comment by philippwulff** [comment] 2021-04-12 11:24
I also ran SUMO with `--log LOGFILE`, but LOGFILE is empty

**Comment by namdre** [comment] 2021-04-12 13:03
Most likely these are bugs related to the highlight functionality. We currently do not have any tests for removing vehicles with highlights or using load / loadState along with highlights. 
We probably do not need to use your exact sequence of commands to track this down but the following would help us out:
- are you using load or loadState to restart the simulation?
- how are the vehicles removed that are causing the problem?

**Comment by philippwulff** [comment] 2021-04-12 13:54
- I do restart the simulation via `loadState()`.
- Vehicles are removed by SUMO when they arrive at their destination. I do not remove them manually.

However the issue happens at some random call of `step()`, not necessarily right after a restart. For some of the highlighted vehicles I also remove the highlight, by calling 
```connection.vehicle.highlight(veh_id, (0, 0, 0, 0), alphaMax=0.01, duration=0.01)```
on those vehicles. Maybe a `removeHighlight()` method is a useful addition to TraCI.

**Comment by namdre** [comment] 2021-04-12 14:49
- I can replicate the issue of highlights remaining visible after calling loadState.
- I cannot replicate highlights remaining visible after normal vehicle arrival
- I cannot replicate the crash

The easiest way to get a replicating example is probably via https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands
If you have such a log, send it along with all the necessary simulation input files

**Comment by philippwulff** [comment] 2021-04-12 16:17
Can one only use `traci.start()` to create this log?

Because I start the SUMO server and connect to it with:
```
self.sumo_process = subprocess.Popen(sumo_cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
conn = traci.connect(port=DEF_REMOTE_PORT, numRetries=100, )
```

and then I make all the calls to SUMO through `conn`.

I tried replacing these lines with
```
traci.start(sumo_cmd, port=DEF_REMOTE_PORT, traceFile="traceFile.txt")
conn = traci.getConnection()
```
but that does not write all of the calls into the traceFile.txt (probably because I make all calls via `conn` and not `traci`)

**Comment by philippwulff** [comment] 2021-04-12 16:48
I ran the last two commands in a loop (like I usually do with the first two commands when restarting SUMO) and after the second iteration was done, there was content in `traceFile.txt`.

I attached all files (.sumocfg with dependencies and the traceFile.txt). Because I added all Vehicles through traci, I do not have a routes file.

[traci_bug_scenario.zip](https://github.com/eclipse/sumo/files/6298404/traci_bug_scenario.zip)

**Comment by namdre** [comment] 2021-04-14 06:00
Unfortunately, the version of sumo you are using has a bug that affects tracefile generation when working with a connection object. 
Yesterday we released sumo 1.9.0 where the tracefile issue is fixed.
Can you try to reproduce your problem with 1.9.0  and send me a new tracefile?

**Comment by philippwulff** [comment] 2021-04-14 09:39
I installed sumo 1.9 and attached the files with the updated traci command log below. Is there a method in TraCI for running a simulation with commands from such a log? Then I could test if this reproduces my issue..

[traci_bug_scenario_V1.9.zip](https://github.com/eclipse/sumo/files/6309904/traci_bug_scenario_V1.9.zip)

**Comment by namdre** [comment] 2021-04-14 10:56
the tracefile is like a runner script.  Just add a few lines at the top to import traci and call it with `python traceFile.txt`
```
import os,sys
sys.path.append(os.path.join(os.environ['SUMO_HOME'], 'tools'))
import traci
```

**Comment by philippwulff** [comment] 2021-04-14 11:01
Ok, thanks I tried it and I need to modify the files to reproduce the issue. I will upload them when I have them

**Comment by namdre** [comment] 2021-04-14 11:03
I couldn't reproduce a sumo crash (`FatalTraCIError: connection closed by SUMO`) with your script.
I saw some errors in regard to vehicle.unsubscribe but after removing those commands, the simulation runs to completion.

**Comment by philippwulff** [comment] 2021-04-14 12:49
I do not get the error which the traci command log raises in the code from which I generated the command log. This is the error from the traci command log:

```
Traceback (most recent call last):
  File "/snap/pycharm-professional/237/plugins/python/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/237/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/philipp/Code/ba_pw/traci_bug_scenario_V1.9/traceFile.py", line 1797, in <module>
    traci.vehicle.subscribe('14', [])
  File "/home/philipp/sumo/tools/traci/domain.py", line 212, in subscribe
    self._connection._subscribe(self._subscribeID, begin, end, objectID, varIDs, parameters)
  File "/home/philipp/sumo/tools/traci/connection.py", line 243, in _subscribe
    result = self._sendCmd(cmdID, (begin, end), objID, format, *args)
  File "/home/philipp/sumo/tools/traci/connection.py", line 181, in _sendCmd
    return self._sendExact()
  File "/home/philipp/sumo/tools/traci/connection.py", line 98, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: The subscription to remove was not found.
```

It is raised by a statement like this in the traci command log:
```
traci.vehicle.unsubscribe('14')
traci.vehicle.subscribe('14', [])
```
However, in my code I only call:

`self.traci_api.vehicle.unsubscribe(veh_id)`

Looking at the previous and subsequent commands, it looks like the logger added `traci.vehicle.subscribe('id', [])` after every `unsubscribe`. That is causing the error above.

I removed these statements in the traci command log, ran it and sumo closed on error with:
```
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).
```

[traci_bug_scenario_V1.9.0_tested.zip](https://github.com/eclipse/sumo/files/6310864/traci_bug_scenario_V1.9.0_tested.zip)

**Comment by philippwulff** [comment] 2021-04-14 13:11
I do not get the error which the traci command log raises in the code from which I generated the command log. This is the error from the traci command log:

```
Traceback (most recent call last):
  File "/snap/pycharm-professional/237/plugins/python/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/237/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/philipp/Code/ba_pw/traci_bug_scenario_V1.9/traceFile.py", line 1797, in <module>
    traci.vehicle.subscribe('14', [])
  File "/home/philipp/sumo/tools/traci/domain.py", line 212, in subscribe
    self._connection._subscribe(self._subscribeID, begin, end, objectID, varIDs, parameters)
  File "/home/philipp/sumo/tools/traci/connection.py", line 243, in _subscribe
    result = self._sendCmd(cmdID, (begin, end), objID, format, *args)
  File "/home/philipp/sumo/tools/traci/connection.py", line 181, in _sendCmd
    return self._sendExact()
  File "/home/philipp/sumo/tools/traci/connection.py", line 98, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: The subscription to remove was not found.
```

It is raised by a statement like this in the traci command log:
```
traci.vehicle.unsubscribe('14')
traci.vehicle.subscribe('14', []) 
```
However, in my code I only call:

`self.traci_api.vehicle.unsubscribe(veh_id)`

Looking at the previous and subsequent commands, it looks like the logger added `traci.vehicle.subscribe('id', [])` after every `unsubscribe`. That is causing the error above.

I removed these statements in the traci command log and now it runs, but throws this error at the very end:

```
Traceback (most recent call last):
  File "/snap/pycharm-professional/237/plugins/python/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/237/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/philipp/Code/ba_pw/traci_bug_scenario_V1.9_tested/traceFile2.py", line 52258, in <module>
    traci.simulationStep()
  File "/home/philipp/sumo/tools/traci/main.py", line 215, in simulationStep
    return _connections[""].simulationStep(step)
  File "/home/philipp/sumo/tools/traci/connection.py", line 308, in simulationStep
    result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)
  File "/home/philipp/sumo/tools/traci/connection.py", line 181, in _sendCmd
    return self._sendExact()
  File "/home/philipp/sumo/tools/traci/connection.py", line 91, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO
```

[traci_bug_scenario_V1.9_tested2.zip](https://github.com/eclipse/sumo/files/6311003/traci_bug_scenario_V1.9_tested2.zip)

**Comment by namdre** [comment] 2021-04-14 14:54
Excellent preparation! I can now reproduce the crash.

**Closed** 2021-04-14 15:34 UTC
Labels: a:sumo, bug, c:traci

**Comment by philippwulff** [comment] 2021-04-14 16:26
Thanks, this fixed the issue!
