### ISSUE TITLE
Sub-lane model vehicles overlap 

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#7688] opened 2020-10-14 03:12 UTC
When using the sub-lane model, vehicles will occasionally overlap. What is the problem?

**Comment by behrisch** [comment] 2020-10-16 13:39
Maybe you defined an edge length, see #6305

**Comment by namdre** [comment] 2020-11-19 11:59
duplicate of #7718

**Closed by namdre** 2020-11-19 11:59 UTC
Labels: c:sublane, question
