### ISSUE TITLE
vehicle ignores the distance between vehicles

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#12405] opened 2023-01-07 11:35 UTC
hello, sumo developers, the question is that the vehicle ignores the distance between vehicles when the signal light is set to be all green.
![TL](https://user-images.githubusercontent.com/59630993/211148564-0e996731-312d-4e04-a3e7-4713847d7dc3.png)
![TL1](https://user-images.githubusercontent.com/59630993/211148566-3ee63f89-1982-49bd-9922-f1711c4714c0.png)
![TL2](https://user-images.githubusercontent.com/59630993/211148567-fa97a281-9c20-4903-b350-b80e66268036.png)

**Comment by namdre** [comment] 2023-01-07 14:02
duplicate of #12404

**Closed by namdre** 2023-01-07 14:02 UTC
