### ISSUE TITLE
meso: impatience

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5830] opened 2019-07-12 10:20 UTC
Am I correct that there is no impatience in meso?
Is there any way this could be modeled?
I have some issues for vehicles waiting very long at certain highly used unsignalized intersections. I could use other teleporting values, but they would also apply to tls, which I am happy with. 
A teleporting for non-tls waiting time might be a solution.

Thanks!
Lukas

**Comment by namdre** [comment] 2019-07-12 14:49
You are correct. Impatience at unsignalized intersections is not taken into account in meso. Technically, the vehicles grow impatient but the formula that checks whether impatient vehicles can cut it in without accident (forcing foe traffic to brake hard) does not receive the necessary inputs.

Solving this with another teleport threshold would carry the disadvantage of generating even more teleport-warnings (for something that isn't an exceptional situation). I'd rather see this fixed by letting meso make use of vehicle impatience:
 - Setting reasonable values for arrivalSpeedBraking and arrivalTimeBraking in MELoop::setApproaching
 - if eventTime - currentTime > timeToBrakeAtSegmentSpeedLimit, arrivalTimeBraking =  evenTime + TIME2STEPS(30)

**Comment by ambuehll** [comment] 2019-07-15 07:42
OK, makes sense. that would be great. Thanks!

**Comment by ambuehll** [comment] 2019-08-15 08:45
I am sorry to bring this up again, but this is a major issue for large-scale OSM derived networks. Most of my teleports arise due to this issue. Do you have any plans for implementing the meso impatience?

**Comment by namdre** [comment] 2019-08-15 10:22
I'll see if I can find some spare time. Most likely I have to delay this until the release of version 1.3 next week.

**Comment by namdre** [comment] 2019-08-15 22:36
Try the following patch:
[diff.workOn5830.txt](https://github.com/eclipse/sumo/files/3507397/diff.workOn5830.txt)

**Comment by ambuehll** [comment] 2019-08-16 12:20
I am trying to build sumo, but I run into:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\utils_geom.lib(GeoConvHelper.cpp.obj) : error LNK2019: unresolved external symbol proj_create referenced in function "public: __cdecl GeoConvHelper::GeoConvHelper(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class Position const &,class Boundary const &,class Boundary const &,double,double,bool,bool)" (??0GeoConvHelper@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVPosition@@AEBVBoundary@@2NN_N3@Z)
`
Here is my Cmake [cache file](https://drive.google.com/file/d/1Aahx18ZGbuUB0OSiirt75sGPIUHQ7GAd/view?usp=sharing)

**Comment by namdre** [comment] 2019-08-19 07:06
I'm not sure why sumo would fail to build this way. Since I mostly build
SUMO on Linux, my collegue Pablo is better suited to answer this question.
Please open up a ticket for this build failure and I'll assign it to him.

Am Fr., 16. Aug. 2019 um 14:20 Uhr schrieb ambuehll <
notifications@github.com>:

**Comment by ambuehll** [comment] 2019-08-19 07:47
Thanks. I am still working on it. No worries, I'll ask some office colleagues with more experience on compiling, before I bother you again. Let me try some workarounds first.

**Comment by ambuehll** [comment] 2019-08-20 14:34
Worked! 
It decreases the number of teleports by **30%**. Great improvement. Thanks so much!
Is this going to be included in future nightly builds?

**Comment by namdre** [comment] 2019-08-26 13:10
FYI. I intend to include it this week (after tomorrows hotfix release).

**Comment by namdre** [comment] 2019-08-28 14:56
I discovered that the implementation does not work as intended. Basically, the modified values (arrival time and speed when braking because a vehicle from the minor road enters the intersection) would have to be updated while the vehicle with priority approaches an intersection. This happens in micro but not in meso. 
With the patch I sent you, the intersection will be used simultaneously by conflicting streams. Thus a different solution is needed.

**Comment by ambuehll** [comment] 2019-08-29 07:59
Thanks for the information! 
About the conflicting streams: I understand that this is not the case in the current default meso sim, but in general, I don't see a problem with a certain amount of conflicting streams (with certain constraints) for a **mesoscopic** simulation. Isn't the tls-penalty creating conflicting flows as well, as it scales the travel time over an intersection?

**Closed** 2019-08-29 09:34 UTC
Labels: c:meso, enhancement

**Comment by namdre** [comment] 2019-08-29 09:37
The current fix is a very simple mesoscopic interpretation of impatience: if impatience is at maximum, the vehicle passes the priority intersection. The time to reach maximum impatience can be configured by option --time-to-impatience. At the default of 300s this acts basically like a teleport without the warning. You can still configure more-impatient vehicle types that start with a base impatience above 0.
