### ISSUE TITLE
WebWizard fails with ubuntu installation (from ppa:sumo/stable) / issues with sumolib.checkBinary

### ISSUE THREAD

**Issue by leoluecken** [eclipse/sumo#5020] opened 2019-01-10 14:08 UTC
osmWebWizard doesn't work, since sumolib.checkBinary() does not find the binaries as they are not in $SUMO_HOME/bin (==/usr/share/sumo/bin), but in /usr/bin

- [ ] Proposed solution: introduce SUMO_BINDIR and use it as fallback prior to $SUMO_HOME/bin in checkBinary().

- [x] Further, the fallback to name+"D" at the end of checkBinary() is questionable. If nothing is found this leads to checkBinary("sumo") returning "sumoD".

- [ ] And, if the binDir argument is given explicitely, the fallbacks should not be used but an error should be reported if the file is not located where specified.

(tested with SUMO1.1 on xubuntu 16.04 and ubuntu 18.04)

**Comment by namdre** [comment] 2019-01-10 14:37
duplicate of #5000. The invalid sumoD fallback was already fixed. I'm keeping this open due to the other points

**Comment by behrisch** [comment] 2019-01-11 09:50
I do not like the idea of SUMO_BINDIR. We had this once and people did not use it but relied on SUMO_HOME, so I think the symlink is the better solution.
@leoluecken Please recheck with the most recent ppa package whether the symlink and osmWebWizard work.

**Comment by behrisch** [comment] 2019-04-03 21:14
Seems to be fixed now, please reopen if problems persists

**Closed by behrisch** 2019-04-03 21:14 UTC
Labels: bug, c:pytools, release
