### ISSUE TITLE
add vehicle attribute 'arrivalEdge' to allow ending at an arbitrary edge along the route (similar to ref #1129)

### ISSUE THREAD

**Issue by ArmelliniMG** [eclipse/sumo#8238] opened 2021-02-16 19:14 UTC
For PT definitions it would be useful to be able to define shorter routes based on a longer one, by defining departure and arrival edges. The attribute 'departEdge' has already been implemented in #1129.

**Comment by namdre** [comment] 2021-02-16 19:42
duplicate of #7609

**Closed** 2021-02-16 19:43 UTC
Labels: a:sumo, c:input, duplicate, enhancement
