### ISSUE TITLE
Problem with Blue light device when handling more interacting devices

### ISSUE THREAD

**Issue by lbieker** [eclipse/sumo#4629] opened 2018-09-21 08:21 UTC
An error occurs if a vehicle with a blue light device requests another vehicle with a blue light device to build an emergency vehicle lane.

**Comment by namdre** [comment] 2018-09-21 08:55
@bieker could this be a duplicate of #4531 ?

**Comment by Bieker** [comment] 2018-09-21 08:59
Sorry, I am to new to understand.

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Jakob Erdmann <notifications@github.com>
Verzonden: Friday, September 21, 2018 10:55:22 AM
Aan: eclipse/sumo
CC: Bieker; Mention
Onderwerp: Re: [eclipse/sumo] Problem with Blue light device when handling more interacting devices (#4629)


@Bieker<https://github.com/Bieker> could this be a duplicate of #4531<https://github.com/eclipse/sumo/issues/4531> ?

**Comment by Bieker** [comment] 2018-09-21 09:03
I have a FxChipBlue but did not got it working. I now first focus on a proper working Freelap under Relay coach with FxChip. Did this answer satisfy?

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Jakob Erdmann <notifications@github.com>
Verzonden: Friday, September 21, 2018 10:55:22 AM
Aan: eclipse/sumo
CC: Bieker; Mention
Onderwerp: Re: [eclipse/sumo] Problem with Blue light device when handling more interacting devices (#4629)


@Bieker<https://github.com/Bieker> could this be a duplicate of #4531<https://github.com/eclipse/sumo/issues/4531> ?

**Comment by Bieker** [comment] 2018-09-21 09:12
I meet the problem of a deliverd FxChip which has a different code sticker than showed on the screen. I scedule it later to come back on it

**Closed** 2018-09-25 12:33 UTC
Labels: a:SUMO, bug
