### ISSUE TITLE
Netedit does not handle E1 detectors correctly

### ISSUE THREAD

**Issue by jprk** [eclipse/sumo#5071] opened 2019-01-18 19:22 UTC
When editing E1 detectors with `Netedit`, detectors with negative `pos` values (i.e., according to [documentation](http://sumo.dlr.de/wiki/Simulation/Output/Induction_Loops_Detectors_(E1)), the position specified as distance from the end of the lane) are placed at `pos=0`, see the attached screenshot:
![sumo_e1_pos_error_netedit](https://user-images.githubusercontent.com/5995093/51407529-6e1f5880-1b5c-11e9-9f12-2308d1d22a11.png)
When saving, I get another warning:
![sumo_e1_pos_error_netedit_save](https://user-images.githubusercontent.com/5995093/51407861-585e6300-1b5d-11e9-99d6-f9a25cfac0ca.png)

When I try to read in the detector file (additionals) saved by netedit, the offending E1 detector is not included in the model with the warning

```
Warning: Invalid position for e1Detector with ID = 'e1_negative'.
```

`sumo-gui` seems to handle the negative `pos` value correctly.

Actually, specifying detector position as the distance from the end of the lane make a lot of sense in urban scenarios: If you replicate the intersection based on traffic authority documentation, at least the drawings I have seen here have all loop distances measured backwards from the stop-bar. It has one additional advantage: if you edit the lane and move the upstream end (e.g. due to recomputation of upstream intersection shape), the detector remains at its former place. The only way how to accomplish this now seems to be repetitive manual editing of `.det.xml` file with additionals, and loading it into `sumo-gui` to check whether the detectors are at their positions...

**Comment by namdre** [comment] 2019-01-18 22:45
I fully agree and this will be fixed. I'm closing this because it's a duplicate of #4924

**Closed by namdre** 2019-01-18 22:45 UTC

**Comment by namdre** [comment] 2019-01-21 08:18
@jprk #4924 is fixed
