### ISSUE TITLE
Continuous stop and restart on the internal lane

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11886] opened 2022-10-25 04:17 UTC
Is there a way to set multiple stop coordinates on the internal lane in SUMO, and can it be stopped and restarted continuously but not use the traci.vehicle.setStop method more than once? If not, how do you stop and start and stop again in sumo? I understand that the traci.vehicle.setStop () method can stop the vehicle after a certain distance from the start of the lane, but is there a way to set multiple stops?
**SUMO-version:**

**Comment by m-kro** [comment] 2022-10-25 05:57
Duplicate of #11885

**Closed by m-kro** 2022-10-25 05:57 UTC
Labels: duplicate
