### ISSUE TITLE
Special shared road: tram/rail_urban way with vehicles not simulatable with standard elements

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#5850] opened 2019-07-25 12:37 UTC
I'm simulating real city situations, where there are streets, where one of the lanes in a x lane street is used together by tram/S-Bahn/U-Bahn and normal vehicles. If I want to simulate the interaction, I have to create an edge, where the allowed list contain the tram, rail_urban.
When I import such an area from OSM, I become a net, where there is a 'normal' edge covered by a rail edge, and they use the same junctions. I have to delete all rail edges and include the 'tram, rail_urban' to the allowed types.
There is no such road type predefined, where such combination exists, therefore netconvert drops an error during creating net from no-internal to internal lanes. I can ignore it, but this is not an appropriate solution.
There are such real world sites, so it needs a standardised solution.

**Comment by namdre** [comment] 2019-08-05 12:03
I agree that it would be good to handle overlapping road/rail elements from OSM automatically and turn them into sumo lanes with merged permissions. This is compliated by the fact the the osm ways don't always share all intermediate osm nodes. But at  least the cases where they do could be handled.

The error during network creation is still unclear to me. Can you quote the exact error output?

**Comment by ZoltanBaksa** [comment] 2019-10-17 13:05
Hello Jakob,
I have started to update the OSM data accordingly. Do you plan to use the relevant osm tags (embedded:_rails and embedded_rails:lanes?
The error during network creation did not occurred again after you corrected --no-internal-links false option in #5836

**Comment by namdre** [comment] 2019-10-23 13:01
So far I've relied on the road having both 'highway' and 'railway' keys to convey this information.
I notice, that the embeded_rails tag is used very seldomly (only 4000 times in the global dataset) but I don't mind supporting it (essentially interpreting its value as if it came from a railway key).

Feel free to send me a nice small piece of sample osm data for a test.

**Comment by namdre** [comment] 2020-05-06 12:23
duplicate of #6980 (the other ticket has example inputs so I'm keeping that one)

**Closed by namdre** 2020-05-06 12:23 UTC
Labels: a:NETCONVERT, duplicate, enhancement
