### ISSUE TITLE
"saveState", "loadStateState" in "Change Simulation St"

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#9782] opened 2021-12-14 00:25 UTC
Hello.

While running the simulation, an unknown error is occurring in the process of saving and reloading the state value.

1. Initially, I set the time as below and proceeded with the simulation.
(I used unix time.)
begin : 1633039800 ~ end : 1633040099

2. And the last state value is saved using traci.sumulation.saveState(file_name).

3. After setting begin: 1633040100, running the next simulation and loading the saved state value, the following error occurs.
![image](https://user-images.githubusercontent.com/62294108/145910243-3524417d-15d0-45b2-bf59-042410dc4ddd.png)

And when I enter the save_state.xml file, the vehicletransfer time is set excessively large as shown below. I think the decimal point is probably missing.
![image](https://user-images.githubusercontent.com/62294108/145910331-95a4ab73-6fef-4069-b17f-f7bd239afb74.png)

May I know what could be the cause of this error?

**Comment by sky4994** [comment] 2021-12-14 00:29
I'm having the same problem
Reducing traffic will not cause that problem.
But I want to simulate with realistic traffic volume. How do I solve this problem?

**Comment by namdre** [comment] 2021-12-14 06:49
sumo stores times internally as milliseconds

**Comment by namdre** [comment] 2021-12-14 08:33
I cannot reproduce the error. Most likely, your SUMO_HOME variable points to an outdated version of data/xsd/state_file.xsd so what you are seeing is a duplicate of #8926

**Closed by namdre** 2021-12-14 08:33 UTC
Labels: duplicate
