### ISSUE TITLE
intersection look abnormal when use --junctions.join

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#8852] opened 2021-07-22 00:47 UTC
hello, sumo developer, i use the --junctions.join to join the juction when use netconvert to convert osm network into sumo network,   but the node/intersection look abnormal when use --junctions.join (like picture 1 and 2).Could you tell how to deal with this problem,thank you so much.
![1](https://user-images.githubusercontent.com/59630993/126576898-2c30f5ab-92db-4d6c-91bb-56d78aaf53d1.png)
![2](https://user-images.githubusercontent.com/59630993/126576900-9b8b1c63-f3c3-4ab4-9ed7-95b0a36f2602.png)

**Comment by chen-98** [comment] 2021-07-22 02:44
![image-20210722104201385](https://user-images.githubusercontent.com/49219212/126583329-4ca08969-8cde-42d4-9619-496105e3f1a2.png)
the same problem,

**Comment by behrisch** [comment] 2021-07-22 16:19
Can you share your input or at least the coordinates you use and the precise netconvert call?

**Comment by zhaotuo0815** [comment] 2021-07-23 01:46
here is the OSM file that convert from shp file,and the convert call is "netconvert --junctions.join true --osm-files shahe.osm -o test.net.xml".


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eclipse/sumo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月23日(星期五) 凌晨0:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eclipse/sumo] intersection look abnormal when use --junctions.join (#8852)





 
Can you share your input or at least the coordinates you use and the precise netconvert call?

**Comment by behrisch** [comment] 2021-07-23 06:02
Can you attach the file directly to the ticket, email attachments do not seem to work? If I understand correctly you created the osm file from a shapefile. Is there any reason for not importing the shapefile directly? And which tool did you use to convert it? Can you share the shapefile as well?

**Comment by chen-98** [comment] 2021-07-23 08:11
1. The problem occur when using --lefthand. Without this option , result seems to be right,
2. When import shapefile directly, we met problem: `ERROR 1: OGRProjCT::Initialize(): if source and/or target CRS are null, a coordinate operation must be specified` So, we write our own scripts to convert. That lead to the next problem.
3. After modify the osm file to aviod topotaxy error by ensure nodes do not overlap each other unless they are the same node.  --junctions.join seems to be invalid.
attached the osm file(file type was changed to upload) and netconvert call
`netconvert --keep-edges.by-type highway.trunk,highway.motorway,highway.motor_link,highway.primary,highway.primary_link,highway.secondary,highway.secondary_link,highway.tertiary --roundabouts.guess
--junctions.join-dist 20            
--osm-files shahe.osm -o shaheroad.net.xml`
[shahe.txt](https://github.com/eclipse/sumo/files/6867417/shahe.txt)

**Comment by behrisch** [comment] 2021-07-23 09:55
Thanks. Can you open a separate ticket for point 2 and attach the shapefile there?

**Comment by behrisch** [comment] 2021-07-23 10:03
> 
> 
>     1. The problem occur when using --lefthand. Without this option , result seems to be right,

This may be a stupid question but why do you use lefthand here? This does not seem to originate from a region where lefthand driving is present. So the results cannot be correct.

In my first tests I could nevertheless not spot the problems immediately. Can you please share the junction or edge ids and also report the SUMO version you are using?

**Comment by chen-98** [comment] 2021-07-24 08:24
> Thanks. Can you open a separate ticket for point 2 and attach the shapefile there?

Sorry, the shp file could not be shared yet. I would try to find other unclassified shp file to reproduce the problem.

**Comment by chen-98** [comment] 2021-07-24 08:38
> > ```
> > 1. The problem occur when using --lefthand. Without this option , result seems to be right,
> > ```
> 
> This may be a stupid question but why do you use lefthand here? This does not seem to originate from a region where lefthand driving is present. So the results cannot be correct.
> 
> In my first tests I could nevertheless not spot the problems immediately. Can you please share the junction or edge ids and also report the SUMO version you are using?

Maybe I misunderstood the concept of lefthand. Because the net is located in China. And the driver's seat is on the left here. So I use the lefthand option. Am I using it right?

See 
junction:1801700000
junction:2146900000
junction:3397300000
junction:4493200000
They should be one junction in the real network. And I think they are close enough to join.

Attached the net file I converted from shehe.txt.
[shaheroad.net.zip](https://github.com/eclipse/sumo/files/6872123/shaheroad.net.zip)

**Comment by chen-98** [comment] 2021-07-24 08:40
![image](https://user-images.githubusercontent.com/49219212/126862899-bcdae026-4094-4af6-bb92-766a91aa7e0b.png)

**Comment by namdre** [comment] 2021-07-26 05:54
The lefthand option should only be used in areas with left-hand traffic rules. Driver seat position is not relevent for network layout.
https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic

**Comment by chen-98** [comment] 2021-07-26 08:46
> The lefthand option should only be used in areas with left-hand traffic rules. Driver seat position is not relevent for network layout.
> https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic

Thank you! But the join problem still unresolved.

**Comment by namdre** [comment] 2021-07-26 09:19
![grafik](https://user-images.githubusercontent.com/6240630/126965224-1dee0100-c96f-438e-80ae-bf8582daf44c.png)

Some of your road edges are defined in the wrong direction (roads running east-west) in the attached screenshot are wrong whereas roads running north-south are fine. This must be fixed in your input data and cannot be handled with netconvert options.

**Closed by namdre** 2021-07-26 09:19 UTC
Labels: question
