### ISSUE TITLE
Taxi stops at end of edge

### ISSUE THREAD

**Issue by rklshbl** [eclipse/sumo#8422] opened 2021-03-25 14:37 UTC
The taxi using the randomCircling behavior passes the edge multiple times without any problems. At some point in the simulation however the taxi stops at the end of the edge with no warning or error. After some time the taxi is teleported with the warning that it was located on the wrong lane.
[Scenario_Github.zip](https://github.com/eclipse/sumo/files/6205288/Scenario_Github.zip)

**Comment by namdre** [comment] 2021-03-25 14:45
I'ts a known issue. The recommended workaround is to only use randomCircling in networks without dead-ends.

**Comment by namdre** [comment] 2021-03-26 09:01
Actually, your attached scenario has no dead-ends and the problem you saw was a duplicate of #8423

**Closed by namdre** 2021-03-26 09:01 UTC
Labels: a:sumo, bug, c:taxi, duplicate
