### ISSUE TITLE
Stuck left turn vehicles

### ISSUE THREAD

**Issue by lola-notraffic** [eclipse/sumo#10858] opened 2022-06-01 13:23 UTC
note: follow-up to #10846

Hello,

We have noticed that sometimes left turn vehicles stuck in the middle of the intersection during the simulation. When investigating we saw  that when opposite direction right turn vehicles approach the intersection, left turn vehicles stop in the middle of the intersection.
We investigated till we found the source of the problem (presented below), but we don't know how to fix it.

Problem Example:
left turn vehicles - direction -northbound left turn
right vehicle - direction - southbound right turn

1. Before left turn vehicle starts moving (before entering intersection): has a good valid route:

![image](https://user-images.githubusercontent.com/95179338/171410079-3828464f-6e81-4b8d-a50e-43c774bcad42.png)

2. Entering the intersection: the left turn vehicle: the route had changed while the vehicle inside:

![image](https://user-images.githubusercontent.com/95179338/171410636-a3182dd2-a541-44d0-a329-6d2bd1f0fed9.png)

this changed route inside the intersection has a collision with right turn vehicle waiting in the queue with left turn vehicles from the opposite direction. When this "collision" occurs left vehicle stops:
![image](https://user-images.githubusercontent.com/95179338/171412460-d95ede09-2dba-465a-adb6-a9d6a9eccf70.png)

3. When the left turn vehicle exits the intersection the route updated back to the route we expect as defined in connections.
![image](https://user-images.githubusercontent.com/95179338/171413864-44e07a3b-f6f3-4cff-b6b7-182f31a0fc47.png)

Our connections in the junction:
![image](https://user-images.githubusercontent.com/95179338/171394284-b5e65d98-4596-4a66-9cde-8a42343cc8ae.png)

Things we tried to test too:
1. When deleted the right turn vehicle (direction: southbound to the right), then the left turn vehicles did not stuck in the simulation.
2. We added contPos = 0 for left turns for them not to enter the intersection unless they cross for sure. Did not help.
3. we ran --no-internal-links true as an option that help, but we want the vehicles to pass the whole intersection properly.
   
So why this change in lanes happens inside the junction? how it can be fixed?

**SUMO-version:*1.9.2, 1.13.0*

**operating system:*ubuntu 20.04*

**Comment by lola-notraffic** [comment] 2022-06-01 14:10
@namdre I saw you added the fix. How can we get a new version? We are working with sumo docker and python traci.

**Comment by lola-notraffic** [comment] 2022-06-01 14:14
Got it. Thank you!

**Comment by namdre** [comment] 2022-06-01 14:18
> When deleted the right turn vehicle (direction: southbound to the right), then the left turn vehicles did not stuck in the simulation.

Looking at your first screenshot (where the right-turning vehicle is at the back of the queue), this could be a duplicate of #4811

**Comment by behrisch** [comment] 2023-02-18 15:05
closing for lack of feedback, please add a comment if you can share more info

**Closed by behrisch** 2023-02-18 15:05 UTC
Labels: question, awaiting reply
