### ISSUE TITLE
Could not open the site ''http://sumo.dlr.de''

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#4150] opened 2018-06-01 20:11 UTC
The site "http://sumo.dlr.de" could  not be opened, even thongh different browers have beed used to have a try. I have tried to go to the website for a couple of days, but it could not be work.  Is there someting wrong with the website ? 
Appreciate for your reply.

**Comment by namdre** [comment] 2018-06-01 23:31
Hello,
we are experiencing a network problem that prevents outside access to our main documentation server.
We will notify the user list once the problem is fixed.
In the meantime, please use our backup documentation at http://sumo.sourceforge.net which is updated daily

I'm closing this ticket as it is a duplicate of #4111

**Closed by namdre** 2018-06-01 23:31 UTC
