### ISSUE TITLE
Time got by TRACI  do not match the the time showing in GUI  

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#5809] opened 2019-07-05 20:36 UTC
As  what has been attached as one picture, the time set and got by TRACI is one second faster that the one shown in GUI .
![problem)1](https://user-images.githubusercontent.com/39317241/60744227-8e8c7500-9f3a-11e9-8095-f748b5ceed01.png)

**Comment by fengbaozhiling1** [comment] 2019-07-07 06:32
Why don't you minus one.

**Comment by namdre** [comment] 2019-07-07 19:55
duplicate of #1463

**Closed by namdre** 2019-07-07 19:55 UTC
