### ISSUE TITLE
SUMO GUI: Closing the view settings / visualisation settings window hides the sumo gui window

### ISSUE THREAD

**Issue by jalemann** [eclipse/sumo#12014] opened 2022-11-10 13:29 UTC
Add your issue description here.
If I open the view settings / visualisation settings in sumo gui and I close the settings window (e.g. by clicking OK or Cancel) the whole sumo gui window closes (or crashes) as well. This happens even when not changing anything in the view settings.

*If possible, upload an example that shows your problem.*
Can do if it helps, but where?

**SUMO-version:**
1.15

**operating system:**
MacOS 13 - Ventura (tested on 13.0 and 13.0.1)

**Comment by jalemann** [comment] 2022-11-10 13:45
After locking and returning to my screen the sumo gui windows reappeared, so they didn't get closed but rather hidden or moved somewhere where I cannot access them.

The workaround is to lock the Mac and unlock it again after using sumos view settings.

**Comment by namdre** [comment] 2022-11-10 13:59
can you use the task manager to switch back to the sumo-gui window?

**Comment by jalemann** [comment] 2022-11-10 14:10
No or at least couldn't figure out how. However I found another thing to get the window back: One can use the Mission Control feature (swiping three fingers up) to bring up all windows that are open somewhere on the Desktop, there is a big invisible area which when hovered over reveals to be the invisible sumo gui window. Clicking it makes it visible and accessible again.

So the sumo gui window is made invisible and moved somewhere (maybe out of desktop bounds)?
<img width="2047" alt="Screenshot 2022-11-10 at 15 10 06" src="https://user-images.githubusercontent.com/58050402/201113751-d7bd8cde-7c27-42c5-82ff-196e6bccb664.png">

**Comment by angelobanse** [comment] 2022-11-10 16:43
I can reproduce this bug. It happens after closing the view settings dialog (it also affects `About`, `Edit viewport`, and all the `Open` dialogs in the File menu).

@jalemann as a quick workaround you can also get the window back by right-clicking on the XQuartz icon on the dock and manually selecting the window:
![Captura de pantalla 2022-11-10 a la(s) 17 43 21](https://user-images.githubusercontent.com/16121932/201155231-870a82cb-6b60-49d8-9240-4b1d9512251a.png)

**Comment by namdre** [comment] 2022-11-10 21:04
does it also affect netedit?

**Comment by jalemann** [comment] 2022-11-10 21:43
@namdre yes, just tested it

**Comment by namdre** [comment] 2022-11-11 07:31
@angelobanse re:regression:  Can you determine the last release version where the bug wasn't present?
Could you also do a [git-bisect](https://git-scm.com/docs/git-bisect) to find the commit where it broke?

**Comment by angelobanse** [comment] 2022-11-16 09:25
This bug appears to be recently introduced by an external library (maybe fox?), and not by us.
When building old SUMO releases, i now see this undesired behavior there too (where I'm positive it didn't happen before).

**Comment by namdre** [comment] 2022-11-16 09:45
If you can roughly pin the error between a good and bad fox-version we can report it on foxgui-users@lists.sourceforge.net

**Comment by angelobanse** [comment] 2022-12-08 12:39
Thank you @ambuehll, i'm also discarding fox as i have downgraded it several versions and can still reproduce this issue. 
Which macOS versions have you on those macs?

**Comment by angelobanse** [comment] 2022-12-08 14:15
It seems to be a macOS Ventura issue, also affecting other projects using X11:
https://github.com/pemsley/coot/issues/68
https://github.com/XQuartz/XQuartz/issues/297
https://github.com/XQuartz/XQuartz/issues/293

Apparently it has already been reported to Apple through their [feedback system](https://bugreport.apple.com/) - which is private ...
macOS 13.1 should be released next week, i will test it again after the update.

**Comment by jalemann** [comment] 2022-12-13 21:33
Issue persists on macOS 13.1 unfortunately.

**Comment by ambuehll** [comment] 2023-02-24 20:17
Issue persists on macOS 13.3(beta) unfortunately.

**Comment by ambuehll** [comment] 2023-03-03 13:23
Issue solved with _newest_ macOS Version 13.3 Beta (22E5230e). yayyyy, finally!!! 👍

**Comment by angelobanse** [comment] 2023-03-06 11:56
Let's wait for the stable release of version 13.3, to test, document and finally close this issue. 
Thanks @ambuehll for reporting :+1:

**Comment by angelobanse** [comment] 2023-03-28 08:29
macOS 13.3 was released yesterday, and indeed (finally) fixes this bug.

**Closed by angelobanse** 2023-03-28 08:29 UTC
Labels: a:sumo-gui, bug, mac, regression
