### ISSUE TITLE
Wrong lane on Developer version

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#11827] opened 2022-10-13 17:14 UTC
Hello, I installed SUMO developer version and set the departLane="best". However, There is still wrong lane problem. So I wonder if there are other solutions for it?
My example and sumo version can be got below:

[wrong_lane.zip](https://github.com/eclipse/sumo/files/9779060/wrong_lane.zip)

![uTools_1665681259495](https://user-images.githubusercontent.com/62609436/195662638-07247c66-a8fe-4f7f-ba27-0a988dfd3524.png)

Thank you!

**Comment by m-kro** [comment] 2022-10-14 11:11
Please don't open new tickets for the same topic. Duplicate of #11806 .

**Closed by m-kro** 2022-10-14 11:11 UTC
Labels: duplicate
