### ISSUE TITLE
missing data folder in ubuntu package

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4583] opened 2018-09-12 14:15 UTC
reported by  thanos.tas@gmail.com

> i have installed SUMO on Ubuntu 18.04 using sudo apt-get command. The installation went perfectly, but i want to point out that in the usr/share/sumo folder that is created there is not included a data folder, only the tools folder, so when i i run a SUMO configuration file i got the warning.
> 
>  Warning: Cannot find local schema
> > ~/data/xsd/routes_file.xsd', will try website lookup

**Comment by behrisch** [comment] 2018-09-18 18:03
a duplicate of #3802

**Closed by behrisch** 2018-09-18 18:03 UTC
Labels: bug, c:build, sumo-user
