### ISSUE TITLE
apparent freeze in SUMO-GUI due poission definition in person flows

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#10567] opened 2022-04-22 09:42 UTC
See SUMO\tests\netedit\demandelements\personflow\create\poisson

**Comment by namdre** [comment] 2022-04-23 09:57
duplicate of #4008 

The problem is unrelated to poisson flow. It's just extremely dense pedestrian traffic that causes a huge number of warnings.

**Closed by namdre** 2022-04-23 09:57 UTC
Labels: duplicate, a:sumo-gui, bug

**Comment by namdre** [comment] 2022-04-23 10:06
@palvarezlopez If you wish to make the test run without congestion, set `departPos="random"` for the personFlows.
