### ISSUE TITLE
Vehicles overlap on the road

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#8633] opened 2021-05-17 09:09 UTC
Even if I set "minGap = 2.5", the vehicles will overlap on the road. When I increase the minGap value, the vehicles will not overlap on the road, but the vehicles in the intersection will keep a long distance, which is not reasonable.

**Comment by namdre** [comment] 2021-05-17 10:35
duplicate of #8632
Please reply in the original ticket with additional information (i.e. if the response did not solve your problem).

**Closed by namdre** 2021-05-17 10:35 UTC
Labels: duplicate
