### ISSUE TITLE
Is it possible to reset sumo through TraCI API

### ISSUE THREAD

**Issue by ShaoyuanLi** [eclipse/sumo#4724] opened 2018-10-21 08:57 UTC
Hi,

Is it possible to reset sumo through TraCI API?

I would like to control sumo with a drive system, which enables me to reset a running simulation again and again. Is there a API to reset sumo environment？(Sumo connection's initialization and binary program's start-up is too slow even in local.)

With best regards!

**Comment by ShaoyuanLi** [comment] 2018-10-21 09:02
Remove additional 'add'

**Comment by behrisch** [comment] 2018-10-24 16:36
You can trigger a reload just by issuing simulation.load but I assume you mean the network loading is slow and not the startup of the binary itself, so that won't help. So this is probably a duplicate of #2440.

**Comment by TransUMDxSEU** [comment] 2018-11-04 15:14
Hello, you can edit it in the sumocfg file by putting the code below, which will help you automatically start and close the simulation. And then you can restart the simulation by recalling sumocfg file.

<gui_only>
	<start value="t"/>
	<quit-on-end value="t"/>
</gui_only>

**Comment by behrisch** [comment] 2018-11-04 20:10
Yes, these two options help in avoiding the need to click when using the GUI, but they do not speed up anything and especially quit on end may be not desirable, if you want to reload the config. Closing as duplicate of #2440.

**Closed by behrisch** 2018-11-04 20:10 UTC
