### ISSUE TITLE
allow adding routes with stops via traci

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8176] opened 2021-02-02 08:00 UTC
The current route.add only allows a list of edges. Maybe we could also allow the trip semantics giving only from, to and vias (and/or stops serving as vias).

**Comment by behrisch** [comment] 2021-11-09 09:22
An alternative solution is route.addStop

**Comment by namdre** [comment] 2023-06-06 05:36
- trip semantics are implemented by giving a route with two disconnected edges
- addStop idea is duplicate of #13372,

**Closed by namdre** 2023-06-06 05:36 UTC
Labels: enhancement, c:traci
