### ISSUE TITLE
How to change the rou.xml when simulation is going on ? 

### ISSUE THREAD

**Issue by meco2020** [eclipse/sumo#10482] opened 2022-04-04 19:07 UTC
Hello！I have a question about sumo. 
 I want to realize the function of the [website](https://traffic-simulation.de/) in SUMO (change  vehicle number or truck rate during the simulation run).
While I was implementing this function, I found some problems：
1>. I used traci.simulation.saveState to save simulationStep when I changed  vehicle number and truck，and then use traci.simulation.loadState to restart the simulation, but  the vehicle number and truck rate did not change. 
2> Even though the flow in my ***.rou.xml  lasts for quite a long time,  but after I used traci.simulation.loadState, there will be no vehicles on the road in a few miuntes

Hope to get your help，thanks！
————
The compressed package contains all my code and files，and the operation steps are as follows：
step 0： run the .../code/ChangeTruckRate_v2.py ,it will start the .../sim/test4.cfg
step1：change the “E2W_VehicleNumber” and “E2W_1_TruckRate” in .../sim/input.csv ( the E2W_VehicleNumber and E2W_1_TruckRate work on vehicle number and truck number on the edge（id:20）
step2: close the input.csv,then ChangeTruckRate_v2.py change the basic.rou.xml, you will see the flow(id:E2W_MainRoad_Truck)'s vehsPerHour will change. Meanwhile, ChangeTruckRate.p will save current simulation ( I used traci.simulation.saveState) and load the simulation to a new simulation (I start the .../test4.cfg again） 
[change_TruckRate.zip](https://github.com/eclipse/sumo/files/8412457/change_TruckRate.zip)

**Comment by namdre** [comment] 2022-04-05 05:28
Both problems should be fixed in the latest development version (https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version). (You request is essentially a duplicate of #741)

There are alternatives to modifying the route files on disk:
- you can add vehicles dynamically with `traci.vehicle.add`
- you can scale an existing flow by calling `traci.vehicletype.setScale` on it's vType (`setScale` is only available in the latest development version`

If you build a web frontend for sumo that works like the mentioned website, please share your results (if you can).

**Closed by namdre** 2022-04-05 05:28 UTC
Labels: question, c:traci

**Comment by meco2020** [comment] 2022-04-05 07:13
> Both problems should be fixed in the latest development version (https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version). (You request is essentially a duplicate of #741)
> 
> There are alternatives to modifying the route files on disk:
> 
> * you can add vehicles dynamically with `traci.vehicle.add`
> * you can scale an existing flow by calling `traci.vehicletype.setScale` on it's vType (`setScale` is only available in the latest development version)
> 
> If you build a web frontend for sumo that works like the mentioned website, please share your results (if you can).

Thank you very much. I'll update my sumo version tonight to try it.
I've considered using traci.vehicle. add()  but this will lead to complex code logic. If the latest version can't solve my problem, I can try traci.vehicletype. setscale or vehicle.add ()
