### ISSUE TITLE
keep attribute order when loading/saving additionals

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8970] opened 2021-08-18 12:00 UTC
It is easier to do a diff then

**Comment by namdre** [comment] 2021-08-18 12:25
is this a duplicate of #7624 or do want to preserve arbitrary user-supplied attribute order?

**Comment by behrisch** [comment] 2021-08-18 14:10
The reason why I opened it is indeed the same but I thought it would be a good idea in general (not only for busStops).

**Comment by namdre** [comment] 2021-08-18 14:36
whereas #7624 is easy to solve (it's a single fixed order), a general solution would require the input order to be stored at parsing time which requires a lot more effort.

**Comment by palvarezlopez** [comment] 2021-08-25 12:01
Currently not neccesary

**Comment by behrisch** [comment] 2021-09-17 07:35
I needed at least once for a poi file but I admit because of rounding errors it may be not very useful

**Comment by palvarezlopez** [comment] 2021-09-17 08:53
@behrisch I can try it

**Comment by namdre** [comment] 2021-09-17 08:58
Are we in agreement that this has low (2.0 level) priority?

**Comment by palvarezlopez** [comment] 2021-09-17 09:18
I'm not sure. What do you think @behrisch ?

**Comment by behrisch** [comment] 2021-09-17 13:43
yes

**Comment by palvarezlopez** [comment] 2021-09-17 14:41
Continue in #9172

**Closed by palvarezlopez** 2021-09-17 14:41 UTC
Labels: enhancement, wontfix, a:netedit
