### ISSUE TITLE
Possible bug in driving error calculation in EIDM

### ISSUE THREAD

**Issue by quajak** [eclipse/sumo#9878] opened 2022-01-04 15:46 UTC
I was looking at the code for the EIDM and the calculation of the driving error seems incorrect. https://github.com/eclipse/sumo/blob/6288a2914ff7eec24ed2aa65d9eefede453e3398/src/microsim/cfmodels/MSCFModel_EIDM.cpp#L777-L791
Either all the cases following the first two (`>= 0.5` and `< 0.5`) are not needed or the order of the else if cases should be reversed.

**Comment by namdre** [comment] 2022-01-04 17:30
paging @Domsall

**Comment by Domsall** [comment] 2022-01-04 19:58
You are absolutely right. I will change this next week when I am back in office. I will also check the changed results, if they still make sence with the current parameters.

**Comment by Domsall** [comment] 2022-01-12 15:07
I created a pull request with the patch. After the patch has been merged, you can download the newest git-version.
Please check if it works as intended now.

**Comment by namdre** [comment] 2022-01-12 17:15
If it doesn't work as intended, please reopen the ticket.

**Closed** 2022-01-12 17:15 UTC
Labels: a:sumo, c:carfollow, bug

**Comment by quajak** [comment] 2022-01-13 19:56
Thanks for fixing it.
