### ISSUE TITLE
Pedestrians will make a circle before and after crossing the crosswalk

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#7502] opened 2020-09-04 00:56 UTC
In the scene of an intersection, pedestrians will make a circle before and after crossing the crosswalk. What is the reason for this? Is there any way to avoid this phenomenon?

**Comment by namdre** [comment] 2020-09-04 05:27
in sumo-gui and fcd-output they should walk more or less straight. The geometry of the walkingarea defines only the outer shape and the path across the walkingarea is computed dynamically by the pedestrian model.

**Comment by namdre** [comment] 2020-11-19 11:41
duplicate of #7703

**Closed by namdre** 2020-11-19 11:41 UTC
Labels: question
