### ISSUE TITLE
person.movetoXY do not work properly

### ISSUE THREAD

**Issue by yarrumgnay** [eclipse/sumo#4054] opened 2018-05-08 11:35 UTC
test with person.moveToXY in walking state. 

When try moving the person to another lane, the new lane's information seems not update with postProcessRemoteControl. So I cannot get the person's current position.
Is there any way to fix it? Thank you for your help!

**Comment by namdre** [comment] 2018-05-08 13:06
person.moveToXY is not fully implemented. I'm closing this as a duplicate of #2872

**Closed by namdre** 2018-05-08 13:06 UTC
