### ISSUE TITLE
Bicycles' preference for bike paths

### ISSUE THREAD

**Issue by dolevi-tub** [eclipse/sumo#10146] opened 2022-02-12 10:47 UTC
Currently, bicycles do not treat bike paths any different from other lanes in their `bestLane` calculation.

It would be more realistic to have bicycles consider bike paths better than other lanes.

**Comment by namdre** [comment] 2022-02-12 18:32
somewhat related: #9091

**Comment by namdre** [comment] 2022-02-15 12:51
duplicate of #5480

**Comment by namdre** [comment] 2022-02-15 13:06
@dolevi-tub (please continue discussion in #5480)

**Closed by namdre** 2022-02-15 13:06 UTC
Labels: duplicate, a:sumo, c:lanechange
