### ISSUE TITLE
osm netconvert: import lane turning tag

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#8330] opened 2021-03-08 16:30 UTC
Enhancement:

The figures below show that unnecessary turnings are introduced.  
without osm.lane-access:
![image](https://user-images.githubusercontent.com/48930860/110349286-dd08e580-8032-11eb-8f8b-54f3bd41512d.png)

with osm.lane-access ) adds another relation in circle 1:
![image](https://user-images.githubusercontent.com/48930860/110349082-9dda9480-8032-11eb-9346-a2201761cfc3.png)

I suggest either importing turning restrictions according to #1446 with osm tag "turn:lanes", in the example: turn:lanes= through|through|right, or refraining from building turning connections within a certain radius. 
[files ](https://drive.google.com/drive/folders/1zrInd-ofawNrfPXP476waQUGr7Rx0qXp?usp=sharing) with v1_8_0+1578-0096e5a33d

see also 875719846
![image](https://user-images.githubusercontent.com/48930860/110362535-adada500-8041-11eb-83fe-5c036e12be6d.png)

**Comment by namdre** [comment] 2021-04-12 07:45
There are two things at play here
- turning restrictions (#1446)
- connection guessing doesn't handle the case where lanes in the middle of the road rare forbidden

**Comment by namdre** [comment] 2021-12-09 23:01
mostly duplicate of #1446

**Closed by namdre** 2021-12-09 23:01 UTC
Labels: a:netconvert, bug
