### ISSUE TITLE
Set Lateral Alignment in TraCI

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#7280] opened 2020-07-03 23:36 UTC
Hi,

I wrote a code, in TraCI, in order to make vehicles to pull over and stop in a two-lane one-way road and in a specified duration. For the vehicles moving in the right lane, the lateral alignment is set to "right," and the speed is set to 0. Also vehicles in the left lane are forced to change lane to the right lane. When the code is running, the vehicles on the right lane pull over to the right side of the lane and stop. However, the vehicles on the left lane change their lanes and stop in the left side of the right lane. I checked their lateral alignment. Although it is set to "right", they stop in the left side. Please find attached a screenshot of the code. Any help would be appreciated.

Thanks,
Reza.

![Capture](https://user-images.githubusercontent.com/64617116/86501168-6f4e4080-bd64-11ea-9f5a-60b24af380b4.PNG)

**Comment by namdre** [comment] 2020-11-19 11:31
is this still relevant or did you solve your issue?

**Comment by namdre** [comment] 2020-11-19 11:33
duplicate of #7306 (the later ticket has example files)

**Comment by namdre** [comment] 2020-11-19 11:33
duplicate of #7306 but the later ticket has example files

**Closed by namdre** 2020-11-19 11:33 UTC
Labels: duplicate, question
