### ISSUE TITLE
improve lane changing ahead of multi-lane roundabout (trac #3221)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3221] opened 2017-06-20 12:43 UTC
the cooperative lane-changing ahead of the roundabout does not take into consideration lane usage on the entering edge. This may lead to reduced space usage and flow.

Migrated from http://sumo.dlr.de/ticket/3221
```json
{
    "status": "new", 
    "changetime": "2017-06-20T12:43:10Z", 
    "description": "the cooperative lane-changing ahead of the roundabout does not take into consideration lane usage on the entering edge. This may lead to reduced space usage and flow.", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1497962590095611", 
    "component": "microsim - lane change", 
    "summary": "improve lane changing ahead of multi-lane roundabout", 
    "priority": "major", 
    "keywords": "", 
    "time": "2017-06-20T12:43:10Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment] 2018-08-28 15:51
it would help if the calibration constant ROUNDABOUT_DIST_BONUS could be set independently of the lcCooperative parametr

**Comment by namdre** [comment] 2019-05-22 11:57
duplicate of #1807

**Closed by namdre** 2019-05-22 11:57 UTC
Labels: a:SUMO, bug, c:lanechange
