### ISSUE TITLE
Finding the Shortest Route Automatically in SUMO Simulation

### ISSUE THREAD

**Issue by Y-AMDIAZ** [eclipse/sumo#13423] opened 2023-06-15 07:53 UTC
"I am sorry, I didn't understand. I want to use an emergency ambulance to send it to a specific location, marked as point X on the map that I created. . Could you please provide me with the initial steps I should take? I have already created the map and set up the ambulance. Now, I would like to assign the destination to the ambulance and ensure it takes the shortest route. I read [incomplete routes](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#incomplete_routes_trips_and_flows) but there some thing that I didnt understand , so please help me ?

**Comment by m-kro** [comment] 2023-06-15 08:05
Duplicate of #13379

**Closed by m-kro** 2023-06-15 08:05 UTC
Labels: duplicate, question, a:sumo

**Comment by Y-AMDIAZ** [comment] 2023-06-15 08:34
![image](https://github.com/eclipse/sumo/assets/129278941/5219c3ed-ae14-41ee-93b2-c408bb057d34)
![image](https://github.com/eclipse/sumo/assets/129278941/a8a5c064-1670-447e-abb4-888543287346)
![image](https://github.com/eclipse/sumo/assets/129278941/9d780425-cc22-4e25-94fd-55dd2f8779c4)
What is the Probleme here I created TAZ and I will send a Car from Taz 0 to Taz 1 so it gives me erreur ;

**Comment by namdre** [comment] 2023-06-15 08:37
If you want to use taz instead of edges, use attributes`fromTaz` and `toTaz` instead of `from` and `to`.

**Comment by Y-AMDIAZ** [comment] 2023-06-15 08:47
I hope you understand me and my issue because my problem is that I want to go from Point X to Point Y. So, I just want to provide a destination, and the car will go there on its own using the shortest route. What I would like is to use Taz based on the documents I have read, but it doesn't seem useful. Can it be used by the edges, or do I have to use Taz? I don't want to manually specify the edges like E1, E2, E3. I just want to provide the destination, and it will go there on its own. I hope someone understands me. I hope... 
![image](https://github.com/eclipse/sumo/assets/129278941/e2702e7c-dbaa-4081-b50a-0d36b4f05780)

**Comment by Y-AMDIAZ** [comment] 2023-06-15 08:57
I would like to understand how SUMO determines the shortest path. Does it consider factors such as the number of vehicles on the road, the distance, or the time it takes to reach a junction ?

**Comment by namdre** [comment] 2023-06-15 09:04
see
https://sumo.dlr.de/docs/Demand/Importing_O/D_Matrices.html#describing_the_taz

Am Do., 15. Juni 2023 um 10:47 Uhr schrieb Y-AMDIAZ <
***@***.***>:

**Comment by namdre** [comment] 2023-06-15 09:04
https://sumo.dlr.de/docs/Simulation/Routing.html

**Comment by Y-AMDIAZ** [comment] 2023-06-15 09:12
so should I use Taz ?

**Comment by Y-AMDIAZ** [comment] 2023-06-15 09:17
![image](https://github.com/eclipse/sumo/assets/129278941/c0b65fce-5db9-456b-91bf-592eee974ba4)
![image](https://github.com/eclipse/sumo/assets/129278941/670cb293-cb0c-44ff-83a6-eca61cc167ac)

**Comment by namdre** [comment] 2023-06-15 09:19
it's up to you. You can use use from/to with edges or fromTaz/toTaz with TAZ but then you also have to define the edges that belong to your TAZ.

**Comment by Y-AMDIAZ** [comment] 2023-06-15 10:05
<img width="916" alt="image" src="https://github.com/eclipse/sumo/assets/129278941/b271f811-52e3-4e61-b3ec-263e60b4a591">
<img width="226" alt="image" src="https://github.com/eclipse/sumo/assets/129278941/39df878b-b77d-4f08-9f70-d742b99b8ec8">
<img width="907" alt="image" src="https://github.com/eclipse/sumo/assets/129278941/2550ea8e-b497-4538-b41c-41ac1d78fd55">

**Comment by m-kro** [comment] 2023-06-15 11:09
You have to choose at least one edge for every TAZ.

**Comment by Y-AMDIAZ** [comment] 2023-06-15 12:43
should I define the edge on the X.add like that 
taz id="taz_0" shape="-82.90,67.20 -68.07,81.33 -54.65,65.09 -70.72,52.73 -82.90,67.56 -82.90,67.20" color="blue" edges="<E1> "

**Comment by Y-AMDIAZ** [comment] 2023-06-15 13:12
I add the edge <?xml version="1.0" encoding="UTF-8"?>



<additional xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd">
   
    <taz id="taz_1" edges="<-E1>" shape="168.92,68.54 192.57,71.65 194.22,60.47 175.70,53.32 169.10,68.35 168.92,68.54" color="red">
        <tazSource id="-E1" weight="1.00"/>
        <tazSink id="-E1" weight="1.00"/>
    </taz>
</additional>
but it gives me erreur , I think the probleme in how i make the edges ?

**Comment by m-kro** [comment] 2023-06-16 08:05
Yes, you have two errors in your definition (look at the examples in the [documentation](https://sumo.dlr.de/docs/Demand/Importing_O/D_Matrices.html#describing_the_taz)):

- if you want to use the simple definition, do not enclose the edge IDs in angle brackets (this syntax just indicates a placeholder in the docs)
- if you want to use multiple edges and assign probabilities, you can remove the "edges" attribute of the simple definition

**Comment by Y-AMDIAZ** [comment] 2023-06-16 08:48
I simply want to provide a destination, and the vehicle will autonomously make a decision based on conditions such as traffic jams, time, and distance to determine the shortest route. Some suggest using a tripe, while others recommend utilizing Taz or Taz probability. However, I'm feeling frustrated with the situation.
