### ISSUE TITLE
missing traffic light on rail crossing

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#12765] opened 2023-03-06 13:29 UTC
I would expect a traffic light guarding the rails here
![image](https://user-images.githubusercontent.com/454288/223123696-c0847ccb-1190-4055-a9eb-c328e1a01662.png)

**Comment by namdre** [comment] 2023-03-30 09:12
currently, rail_crossings nodes are only generated if the osm node is tagged with `railway=crossing`. In this case the osm nodes don't have any extra tags.  This might be an oversight but more like the mappers intended this to be modelled by the traffic light at node 26189998 (which only applies to the left turn judging by streetview).

I would consider this a duplicate of #10772

**Closed by namdre** 2023-03-30 09:12 UTC
Labels: duplicate, a:netconvert, bug

**Comment by namdre** [comment] 2024-11-12 13:19
> This might be an oversight but more likely the mappers intended this to be modeled by the traffic light at node 26189998 (which only applies to the left turn judging by streetview).

In reality, the tram also has a traffic light signal but this information is missing in OSM.
