### ISSUE TITLE
allow cooperative lane-changing for other than strategic reasons (trac #2916)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2916] opened 2017-03-07 08:24 UTC
cooperative changing should also be triggered to support other vehicles with speedGain and their own cooperative changes (probably with less speed adjustments).

Migrated from http://sumo.dlr.de/ticket/2916
```json
{
    "status": "new", 
    "changetime": "2017-03-07T08:24:09Z", 
    "description": "cooperative changing should also be triggered to support other vehicles with speedGain and their own cooperative changes (probably with less speed adjustments).", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1488875049870320", 
    "component": "microsim - lane change", 
    "summary": "allow cooperative lane-changing other than strategic reasons", 
    "priority": "major", 
    "keywords": "", 
    "time": "2017-03-07T08:24:09Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by namdre** [comment] 2018-08-28 16:17
duplicate of #1145

**Closed by namdre** 2018-08-28 16:17 UTC
Labels: a:SUMO, c:lanechange, enhancement
