### ISSUE TITLE
Query: How to prevent changes in lane information after adding traffic signals in netedit.

### ISSUE THREAD

**Issue by thilagaguru** [eclipse/sumo#13514] opened 2023-06-28 01:38 UTC
Operating system : Windows 10
Sumo version : 1.12.0

I am working on sumo and I had the requirement to change the junction name and add traffic signals in the network file.
So I used netedit to change junction name and added signals. 

After changing the junction name, I tried to create signals in the junction by selecting the traffic signal icon
![image](https://github.com/eclipse/sumo/assets/36147578/55be3151-531d-45c3-bfc4-22f4b4886aa3)

Then by selecting the junction and 'create' button. 
![image](https://github.com/eclipse/sumo/assets/36147578/5e5477f4-fcec-4d9b-ba7f-861f4e8938e0)
But it threw up warning as below and the traffic signal was not built.

Warning: The traffic light 'Minaminakadori' does not control any links; it will not be build.
Warning: Could not build program '0' for traffic light 'Minaminakadori'

So i reset the connection in Inspect mode and tried to create the singal same as before and traffic signal was successfully built. 

**Issue**
The issue is, In the network file, along with the addition of new junction name and traffic light information, there is also changes observed in some of the lane informations like shape, length, width and speed for some lanes. (Compared **original.net** and **afteraddingsignal.net** file from attached zip folder)
One of the examples are as below. Changes in length and shape of the lane is observed.

Before 

    <edge id=":8503832970_w0" function="walkingarea">
        <lane id=":8503832970_w0_0" index="0" allow="pedestrian" speed="1.00" length="3.76" width="2.00" shape="1515.01,2597.87 1516.97,2598.23 1516.08,2603.17 1514.11,2602.81 1513.66,2601.32 1513.71,2599.32 1514.92,2598.31 1514.81,2598.68 1514.66,2598.96 1514.44,2599.17 1514.13,2599.29"/>
    </edge>

After adding traffic signal

    <edge id=":8503832970_w0" function="walkingarea">
        <lane id=":8503832970_w0_0" index="0" allow="pedestrian" speed="1.00" length="3.70" width="2.00" shape="1515.01,2597.87 1516.97,2598.23 1516.08,2603.17 1514.11,2602.81 1513.82,2601.32 1513.88,2599.32 1514.93,2598.29 1514.85,2598.65 1514.73,2598.94 1514.54,2599.16 1514.27,2599.29"/>
    </edge>

With the same original.net file, I renamed the file **second_afteraddingsignal.net**, did the same above changes and compared the second_afteraddingsignal.net with the afteraddingsignal.net file to check if they both match. But changes are observed. 
It looks like even with the same network file and adding signals to same junction, the lane informations and junction information (shape) and sometimes connection information differs each time. 

I do not want these changes to happen.
Is there any configuration settings to prevent these changes. 
Attaching the network file in the zip folder (Before and after adding traffic signals) 
Screenshot of which junction is changed.
![image](https://github.com/eclipse/sumo/assets/36147578/62bb2cf7-1232-4829-9477-6c6af60037eb)
[network files.zip](https://github.com/eclipse/sumo/files/11888581/network.files.zip)

It would be really helpful if someone could answer the query.
Thanks in advance.

**Comment by namdre** [comment] 2023-06-28 07:49
This is potentially a bug that was already fixed in later versions. Please try with version 1.17.0 and report your findings.
Note that, adding traffic lights may impact internal junctions and thereby change internal lane shapes at the modified junction (this is more of a general remark and doesn't seem be relevant for the changes you observed).

**Comment by namdre** [comment] 2023-06-28 08:15
on a side note: you scenario contains pedestrian infrastructure that is probably not configured as intended. Consider road edge 180205029#17 which has a parallel pedestrian edge 222977391#4. Presumably, 180205029#17 doesn't have regular foot traffic, but still it permits pedestrians to walk and is thus considered shared space. This has implications for the right of way rules at all intersections (note the large gray walkingareas that cover the edge where pedestrian crossings should be located instead).  Never versions of `netconvert` automatically correct this when importing OSM data.
See https://sumo.dlr.de/docs/Tools/Net.html#netdiffpy for how to port over manual network changes.

**Comment by thilagaguru** [comment] 2023-07-03 03:36
> This is potentially a bug that was already fixed in later versions. Please try with version 1.17.0 and report your findings. Note that, adding traffic lights may impact internal junctions and thereby change internal lane shapes at the modified junction (this is more of a general remark and doesn't seem be relevant for the changes you observed).


Thank you so much for you swift reply. 
Using new version has fixed the above mentioned issues.

**Closed** 2023-07-03 06:06 UTC
Labels: question, a:netedit
