### ISSUE TITLE
Accident for specific vehicles in a intersection

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#9817] opened 2021-12-17 02:58 UTC
Hello, I wonder if there are some methods to model accident in the intersection for specific vehicles. According to the documentation, I append the option, --collision.mingap-factor, --collisions.check-junctions and --collision.stoptime, but the occurence of accident is stochastic, how to make a accident in the intersection with specific vehicles? Thank you in advance!
,**SUMO-version:**
1.11
**operating system:**
win10

**Comment by namdre** [comment] 2021-12-17 07:02
duplicate of #9813 
Please don't open up new tickets with the same question. Instead, add comments to your original questions.

**Closed by namdre** 2021-12-17 07:02 UTC
Labels: duplicate
