### ISSUE TITLE
Insertion position parameter of traci.vehicle.add only works for the first edge

### ISSUE THREAD

**Issue by Tokkalosh** [eclipse/sumo#7580] opened 2020-09-23 08:01 UTC
Insertion position parameter of traci.vehicle.add only works for the first edge

e.g.

RouteOne = Edge 1,2,3,4,5...

If Edge 1 is 100 meters long then

traci.vehicle.add( , , ,departPos = 200) will insert the vehicle at the end of edge 1 at the end (100 meters) with the warning:

"Warning: Invalid departPos 200.00 given for vehicle 'Vehicle1'. Inserting at lane end instead."

Please can you let me know if there is any plan for this to work over the entire route and not just the first edge?

The solution at the moment is to define a lot more routes  in the network so vehicles can start at those points. 

Thank you very much.

**Comment by namdre** [comment] 2020-09-23 12:23
The idea is nice and we might do this eventually.
If it helps, you can use traci.route.add(routeID, [edgeStart, edgeEnd]) to define a "trip" between far-away edges and the vehicle will automatically determine a route between them.

**Comment by behrisch** [comment] 2020-09-23 12:36
I'd rather invent departEdge. I think we discussed it before but I could not find a ticket. The semantics of the other departPos values get a little flaky when we allow the pos to go beyond the edge (should "free" also be allowed to go to the next edge and what about negative numbers: from the route end or from the edge end)?

**Comment by namdre** [comment] 2020-09-23 12:41
then its a duplicate of #1129

**Closed by namdre** 2020-09-23 12:41 UTC
Labels: a:sumo, duplicate, enhancement

**Comment by namdre** [comment] 2020-09-25 06:55
@Tokkalosh Starting tomorrow, the development version of sumo supports the 'departEdge' attribute. 
See https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#departedge
https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version
