### ISSUE TITLE
bike not slow down within intersection until being very close to ped

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#11504] opened 2022-09-02 06:18 UTC
Add your issue description here.
(1) as title; it causes then emergency braking. The intersection is connected with bidi edges;pedestrian.striping.dawdling= 0.5

(2) The ped chooses the opposite crosswalk (:j2_c0), not the crosswalk (:j2_c1) in the same walking direction, and then walk back to the right side after passing the crossing. It does not really correspond to the situation in real life.? This is clearer to see when reducing the crosswalk width.

**SUMO-version:**
v1_14_1+0770-37b69a3fd6a
**operating system:**
Windows

**Comment by namdre** [comment] 2022-09-30 10:22
duplicate of the lengthwise-crossing issue described in #11641

**Closed by namdre** 2022-09-30 10:22 UTC
Labels: duplicate, a:sumo, c:sublane, bug, bidiEdge
