### ISSUE TITLE
Stop taxi on edge

### ISSUE THREAD

**Issue by rklshbl** [eclipse/sumo#8437] opened 2021-03-30 13:43 UTC
When using the taxi device with randomCircling behavior, taxis always park at the side of the road for picking up and dropping off passengers. Depending where the passenger is picked up/ dropped off, this is should not always be possible so i tried to let the taxi stop on the road instead of parking beside it.

Using __attr_repr__ gives the necessary attributes for 'rebuilding' a stop with a different stopflag, however the attribute actType can't be passed to traci.vehicle.setStop or traci.vehicle.replaceStop. Next i created a new StopData object with all the information of the stop that i wanted to replace, but again there was no way to pass this object onto a method.

Replacing stops without the actType seems to work fine at the start, after sometime though some taxis disappear or are stuck after stopping. 

Is there a method to recreate the stop with just a different stopflag while preserving all other attributes? If not, is there another way to let taxis stop instead of park when randomCircling?

**Comment by namdre** [comment] 2021-04-06 10:16
this is a duplicate of #6714.  
Replacing stops should work if timed correctly (so that it doesn't interfere with the stop assignment by the taxi device). 
note: the actType is only for information purposes and does not influence simulation behavior (at least not after f1f4744)

**Closed by namdre** 2021-04-06 10:16 UTC
Labels: c:taxi, duplicate, question
