### ISSUE TITLE
script for nightly scenario deployment (trac #2713)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2713] opened 2016-12-06 12:54 UTC
Migrated from http://sumo.dlr.de/ticket/2713
```json
{
    "status": "new", 
    "changetime": "2016-12-06T12:54:06Z", 
    "description": "", 
    "reporter": "behrisch", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1481028846577401", 
    "component": "scenarios", 
    "summary": "script for nightly scenario deployment", 
    "priority": "major", 
    "keywords": "", 
    "time": "2016-12-06T12:54:06Z", 
    "milestone": "1.0.0", 
    "owner": "namdre", 
    "type": "task"
}
```

**Comment by namdre** [comment] 2018-08-29 18:58
duplicate of #2667

**Closed by namdre** 2018-08-29 18:58 UTC
Labels: c:scenarios
