### ISSUE TITLE
Simulation crashes with lateral lane resolution enabled

### ISSUE THREAD

**Issue by HDSFaust** [eclipse/sumo#7572] opened 2020-09-18 10:08 UTC
i have tested this on different sections of my network and it keeps crashing without a log or error message.
to reproduce it just play the sumocfg file.
when lateral lane resolution is disabled it does not crash
[crashingFiles.zip](https://github.com/eclipse/sumo/files/5244839/crashingFiles.zip)

**Comment by namdre** [comment] 2020-09-20 19:29
duplicate of #1997

**Closed** 2020-09-20 19:30 UTC
Labels: duplicate

**Comment by namdre** [comment] 2020-09-20 19:32
The sublane model is not compatible with opposite-direction driving (neigh-elements in the network). Now sumo will quit wtih an error rather than crash. Though you should already have the Warning "Opposite direction driving does not work together with the sublane model" in your log.
