### ISSUE TITLE
The latitude and longitude information is lost when using netconvert to convert the format of sum-net to opendrive.

### ISSUE THREAD

**Issue by radiateboy** [eclipse/sumo#8625] opened 2021-05-14 10:12 UTC
The latitude and longitude information is lost when using netconvert to convert the format of sum-net to opendrive.

cmd:
`netconvert --net-file cy.net.xml --opendrive-output cy.xodr`

**Comment by namdre** [comment] 2021-05-17 07:37
duplicate of #4417 (see that issue for a workaround)

**Closed by namdre** 2021-05-17 07:37 UTC
Labels: a:netconvert, duplicate

**Comment by radiateboy** [comment] 2021-05-17 09:48
okey, thank you very mush. @namdre
