### ISSUE TITLE
xml2csv -> csv2xml with trip files does not yield same file

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#6927] opened 2020-04-21 19:02 UTC
when running xml2csv on a trip file and then back again, there seem to be some issues with the labels.

>     <vehicle art="7231.74" artLane="free" artSpeed="max" m="42167942#3-AddedOffRampEdge" mTaz="61" ="36097" ="42430282#6" az="155" e="DEFAULT_VEHTYPE">

**Comment by namdre** [comment] 2020-04-21 20:15
looks like a duplicate of #6430 to me. Make sure to use sumo version 1.5 or later.

**Comment by ambuehll** [comment] 2020-04-21 20:26
yes, seems so. Sorry, I only looked for open tickets. 
I am using today's build (v1_5_0+1223-1d645199e6), and checked that the tools are up to date.

**Comment by ambuehll** [comment] 2020-04-22 07:24
This is the same issue, but it persists. That's what I meant to say.

**Comment by namdre** [comment] 2020-04-22 09:08
Then please attach a sample input file because I could not reproduce it with my own tests.

**Comment by ambuehll** [comment] 2020-04-22 09:21
https://drive.google.com/drive/folders/1r9o3gBIxfcYTR2hxbdg0nVcTa1PB3n5R?usp=sharing

**Comment by namdre** [comment] 2020-04-22 16:36
I'm pretty sure that the version of csv2xml you are calling outdated. When I run
`csv2xml.py -x ~/dlr/sumo/data/xsd/routes_file.xsd -o out.xml cuttrips.rou.csv`
the resulting xml file is fine.
Check whether your file contains the following fix: https://github.com/eclipse/sumo/commit/a25ce0922ed8548327f37475dd5fa10411a77d70
Maybe you have an older version that comes first in the search path?

**Closed by namdre** 2020-04-22 16:36 UTC
Labels: duplicate

**Comment by ambuehll** [comment] 2020-04-22 18:25
weird, sorry about that. I downloaded the nightly build. anyways, not that important, I'll check later once again.
