### ISSUE TITLE
traci.exceptions.TraCIException: Vehicle 'xxx' is not known.

### ISSUE THREAD

**Issue by Chenyu3194** [eclipse/sumo#13730] opened 2023-08-21 12:40 UTC
Hi,

I'm working on a algorithmus which is able to calculate multiple vehicles's travel time to a specific position. I edited the route file and set the departure time of some vehicle because I want to see the variant travel time. However, when I set the depart time (below) of veh_2 greter than 0, the veh_3 becomes unknown and python reports the error. And when I set the depart time of veh_4 to a value greater than 0 as well as it of veh_2, the veh_2 becomes unknown. I made sure that the order of depart time is increasing from above to beneath. I can't find the reason behind this

route_file is here:

```
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">
    <!-- VTypes -->
    ...
    <!-- Routes -->
    ...
    <!-- Vehicles, persons and containers (sorted by depart) -->
    <vehicle id="veh_1" type="Car" depart="0.00" departLane="first" departPos="base" departSpeed="13.89" arrivalLane="current" arrivalPos="max" arrivalSpeed="current" color="green" route="r_0"/>
    <vehicle id="veh_4" type="Car" depart="0.00" departLane="first" departPos="base" departSpeed="13.89" arrivalLane="current" arrivalPos="max" arrivalSpeed="current" color="green" route="r_3"/>
    <vehicle id="veh_2" type="Car" depart="3.00" departLane="first" departPos="base" departSpeed="8.33" arrivalLane="current" arrivalPos="max" arrivalSpeed="current" color="yellow" route="r_2"/>
    <vehicle id="veh_3" type="Car" depart="3.00" departLane="first" departPos="base" departSpeed="13.89" arrivalLane="current" arrivalPos="max" arrivalSpeed="current" color="green" route="r_0"/>   
    <vehicle id="veh_5" type="Car" depart="40.00" departLane="first" departPos="base" departSpeed="13.89" arrivalLane="current" arrivalPos="max" arrivalSpeed="current" color="green" route="r_1"/>
    <vehicle id="veh_6" type="Car" depart="45.00" departLane="first" departPos="base" departSpeed="13.89" arrivalLane="current" arrivalPos="max" arrivalSpeed="current" color="green" route="r_1"/>
</routes> 
```

and with debug mode the error occured here:

```
while traci.simulation.getMinExpectedNumber() > 0:
    traci.simulationStep()
    
    
    for vehicle_id, desired_pos_data in desired_positions.items():

            
            **route_id = traci.vehicle.getRouteID(vehicle_id)**
            edges_in_route = traci.route.getEdges(route_id)
            current_edge = traci.vehicle.getRoadID(vehicle_id)

```

**SUMO-version:1.18.0**

**operating system: Win11**

**Comment by JenniferHahn** [comment] 2023-08-21 21:50
I am currently facing the same issues (started a few hours ago) even though I have been running my simulation in exactly the same manner as every single day before. 

I am training an RL agent on my sumo traffic simulation and I currently cannot access any specific vehicle output without getting the error.

I made sure that the vehicle is in the sumo.vehicle.getIDList() and also checked that the trip has not been ended yet.

**Comment by robertalms** [comment] 2023-08-23 08:35
@Chenyu3194 Hi, can you attach a minimum example to replicate this behaviour (without python)? Is SUMO actually not inserting the vehicle?

**Comment by anthonyKiggundu** [comment] 2023-08-30 10:54
Hello @behrisch this issue affects other functionality too, just a simple example;
`while step < 1000:
    traci.simulationStep()
   [x, y] =  traci.vehicle.getPosition(vehicle_id)
  ........
  step += 1`

returns 

`File "/usr/local/lib/python3.8/dist-packages/libtraci/libtraci.py", line 4496, in getPosition
    return _libtraci.vehicle_getPosition(vehicle_id, includeZ)
libtraci.libtraci.TraCIException: Vehicle 'veh5' is not known.`

Initial runs do not return the error but after some iterations the error is thrown.
The osm.passenger.trips.xml file contains 
`<routes>
    <vType id="veh_passenger" vClass="passenger"/>
    <trip id="veh0" type="veh_passenger" depart="0.00" departLane="best" from="23809678#1" to="-111833185#0"/>
    <trip id="veh1" type="veh_passenger" depart="3.21" departLane="best" departSpeed="max" from="-4570580#12" to="-38208961"/>
    <trip id="veh2" type="veh_passenger" depart="6.42" departLane="best" from="-339201177#2" to="24243107#2"/>
    <trip id="veh3" type="veh_passenger" depart="9.62" departLane="best" from="1119935543#0" to="-1119854969#0"/>
    <trip id="veh4" type="veh_passenger" depart="12.83" departLane="best" from="292429062#0" to="1165450341#3"/>
    <trip id="veh5" type="veh_passenger" depart="16.04" departLane="best" departSpeed="max" from="-1110752486" to="-320462164#3"/>
    <trip id="veh6" type="veh_passenger" depart="19.25" departLane="best" from="24234486" to="15973619#3"/>
    <trip id="veh8" type="veh_passenger" depart="25.66" departLane="best" from="6227658#2" to="-202817674#8"/>
....
</routes>
`

**Comment by anthonyKiggundu** [comment] 2023-08-30 14:58
The issue does not affect libtraci only but the traci main lib too. I have tried to dig through the base code and my suspicion is with the line `socket.recv()`  in the file `/usr/local/lib/python3.8/dist-packages/traci/connection.py`, specifically the following lines:

 def _recvExact(self):  

        try:  

            result = bytes()  

            while len(result) < 4:  

                t = self._socket.recv(4 - len(result))  

                if not t:  

                    return None  

                result += t  

            length = struct.unpack("!i", result)[0] - 4  

            result = bytes()  

            while len(result) < length:  

                t = self._socket.recv(length - len(result))  

                if not t:  

                    return None  

                result += t  

                print("INSIDE RECEIVED --->>> ", length,  " ----- ", result, " ----- and t is ----", t)  # t here contains  `7 35 !28s b"Vehicle 'veh5' is not known."` .

Is this something to do with the SUMO socket having been terminated?

**Comment by Chenyu3194** [comment] 2023-08-31 08:02
Hello,

It seems that my question raised some similar issues and questions from other people. To be honest, I discussed this with some one else and **for my own situation** I added this line with a for loop:

`    
    present_vehicle_ids = traci.vehicle.getIDList()

    
    for vehicle_id in present_vehicle_ids:
          if vehicle_id in desired_positions:
             desired_pos_data = desired_positions[vehicle_id]
             route_id = traci.vehicle.getRouteID(vehicle_id)
             routes[vehicle_id] = route_id`

and this worked. The vehicle I defined which enters the scenario 5 seconds later than the start of the simulation now won't cause this error. I hope this could be a hint for other with the similar problem.

**Comment by Chenyu3194** [comment] 2023-08-31 08:08
Hello,

It seems that my question raised some similar issues and questions from other people. To be honest, I discussed this with some one else and **for my own situation** I added this line with a for loop:

`while traci.simulation.getMinExpectedNumber() > 0:
    traci.simulationStep()

    present_vehicle_ids = traci.vehicle.getIDList()

    
    for vehicle_id in present_vehicle_ids:
        if vehicle_id in desired_positions:
            desired_pos_data = desired_positions[vehicle_id]
            route_id = traci.vehicle.getRouteID(vehicle_id)`
and this worked. The vehicle I defined which enters the scenario 5 seconds later than the start of the simulation now won't cause this error. I hope this could be a hint for other with the similar problem.

**Comment by Chenyu3194** [comment] 2023-08-31 08:09
Hello,

It seems that my question raised some similar issues and questions from other people. To be honest, I discussed this with some one else and **for my own situation** I added this line with a for loop and this worked. The vehicle I defined which enters the scenario 5 seconds later than the start of the simulation now won't cause this error. I hope this could be a hint for other with the similar problem. The codes are below:

`while traci.simulation.getMinExpectedNumber() > 0:
    traci.simulationStep()
    
    
    present_vehicle_ids = traci.vehicle.getIDList()

    
    for vehicle_id in present_vehicle_ids:
        if vehicle_id in desired_positions:
            desired_pos_data = desired_positions[vehicle_id]
            route_id = traci.vehicle.getRouteID(vehicle_id)
            routes[vehicle_id] = route_id
...(rest of the code)`

**Comment by behrisch** [comment] 2023-09-01 12:47
Can please anyone share a small example scenario here? Our own tests are running without an error.

**Comment by anthonyKiggundu** [comment] 2023-09-01 13:20
Hello, here is the full script I am running.

`#import libtraci as traci
import traci
import os
import sys
import re
import subprocess
import time


sumoBinary = "/usr/local/bin/sumo-gui"
# sumoCmd = [sumoBinary, "-c", "/home/../sumo/tools/_vehicles_only/osm.sumocfg"]

traci.start(sumoCmd)

class On_Board_Unit():
    def __init__(self):
        self.VehId = " "

global AllVehicles
AllVehicles = {}
max_num_veh = 0
trajectoryList = list(range(0,1000))

simTime = 150

step = 0
traci.simulationStep()

while step < 1000:
    traci.simulationStep()
    lstDeparts = traci.simulation.getDepartedIDList()

    if len(lstDeparts) > 0:
        for veh_id in lstDeparts:
            AllVehicles[veh_id] = On_Board_Unit()
            AllVehicles[veh_id].veh_id = veh_id

            if len(AllVehicles) > 0:
                for veh_id in AllVehicles:
                    id = re.search("\d+", veh_id)[0]
                    [xpose, ypose] =  traci.vehicle.getPosition(veh_id)
                    x = str(xpose)
                    y = str(ypose)

                    print("CarID is = %s " % veh_id)
                    print("Positions ", x,y )

    step += 1 `

**Comment by behrisch** [comment] 2023-09-04 05:23
@anthonyKiggundu Thank you! Can you please add the sumocfg, network and route file to make it reproducible? Just attach everything as a zip

**Comment by robertalms** [comment] 2023-09-04 08:44
Hi Anthony,
I ran your scenario, first without python and it runs just fine. `veh 5` finishes its trip at about 86seconds.

When I run your code expample, of course this crashes when calling `traci.vehicle.getPosition(),` the moment `veh 5` has finished its trip. You need to keep a list of your current vehicles in your scenario, so checking vehicles that have been inserted and excited.

Can you please elaborate what your expectation is? I don't see a SUMO issue so far...

**Comment by anthonyKiggundu** [comment] 2023-09-05 10:31
Thanks @robertalms I just walked around the issue using `vehIDList = traci.vehicle.getIDList()`  and checking `if VehId not in vehIDList: continue`.

**Comment by behrisch** [comment] 2023-09-05 15:32
Just to have this clear also for @Chenyu3194 and @JenniferHahn. This is not a workaround but this is the way to handle things. SUMO does not store information about vehicles which have left the simulation and will probably never do so (mainly for saving on main memory). So please always check whether the vehicle is in the simulation before asking for it (or use subscriptions which end automatically if the vehicle leaves). I am closing this ticket but please add another comment if you think your problems have a different origin.

**Closed by behrisch** 2023-09-05 15:32 UTC
Labels: question, c:traci, awaiting reply

**Comment by Boudadits13** [comment] 2023-11-29 14:02
hi i did a taxi simulation with sumo 
whene i added the second taxi it show this error
traci.exceptions.TraCIException: No reservations have been specified for vehicle 'B'

**Comment by robertalms** [comment] 2023-11-29 16:36
> hi i did a taxi simulation with sumo whene i added the second taxi it show this error traci.exceptions.TraCIException: No reservations have been specified for vehicle 'B'

Your problem seems to be unrelated to the issue here. So best is, you open a new issue, describe the problem a bit more specific and, ideally, attach a minimum example with your config files to reproduce the error you face.
