### ISSUE TITLE
Query about attributeerror for using osmwebwizard

### ISSUE THREAD

**Issue by conjurer-Fan-Wu** [eclipse/sumo#11216] opened 2022-07-17 09:03 UTC
Hi, everyone, I used osmwebwizard for the first time. But I cannot even form a map file. The software shows that there are attributeerrors.

OS; Ubuntu20.04
SUMO: 1.14.0

The full log for running osmwebwizard is below:

fanwu@fanwu:~/work/ns3/ns3 old versions/VANET/VANET_sig/map$ python /usr/share/sumo/tools/osmWebWizard.py 
Opening in existing browser session.
Building scenario in '/home/fanwu/work/ns3/ns3 old versions/VANET/VANET_sig/map/2022-07-17-16-58-29'
Downloading map data
200 OK
Converting map data
Written configuration to 'osm.netccfg'
Parsing types from '/usr/share/sumo/data/typemap/osmNetconvert.typ.xml' ... done.
Parsing nodes from osm-file 'osm_bbox.osm.xml.gz' ... 
Found and substituted 22 osm nodes.
done (247ms).
Parsing edges from osm-file 'osm_bbox.osm.xml.gz' ... done (212ms).
Removing duplicate edges ... done.
Warning: Discarding unknown compound 'cycleway.track' in type 'cycleway.track|highway.primary' (first occurence for edge '4067932').
Warning: Discarding unknown compound 'cycleway.lane' in type 'cycleway.lane|highway.secondary' (first occurence for edge '4401967').
Warning: Discarding unknown compound 'cycleway.lane' in type 'cycleway.lane|highway.tertiary' (first occurence for edge '4412886').
Warning: Discarding unknown compound 'usage.main' in type 'railway.light_rail|usage.main' (first occurence for edge '4471817').
Warning: Discarding unknown compound 'cycleway.opposite_lane' in type 'cycleway.opposite_lane|highway.tertiary' (first occurence for edge '4588220').
Warning: Ambiguous railway kilometrage direction for way '25386365' (assuming forward)
Warning: Ambiguous railway kilometrage direction for way '25946680' (assuming forward)
Warning: Ambiguous railway kilometrage direction for way '32572620' (assuming forward)
Warning: Ambiguous railway kilometrage direction for way '32572624' (assuming forward)
Warning: Ambiguous railway kilometrage direction for way '32590428' (assuming forward)
Warning: Discarding unusable type 'waterway.river' (first occurence for edge '59683399').
Warning: Discarding unusable type 'waterway.canal' (first occurence for edge '145662520').
Warning: Discarding unusable type 'railway.razed' (first occurence for edge '235499467').
Parsing relations from osm-file 'osm_bbox.osm.xml.gz' ... 
Warning: Ignoring restriction relation '1385351' with unknown to-way.
Warning: No way found for reference '374734383' in relation '3904270'
Warning: No way found for reference '32805741' in relation '3904270'
Warning: Ignoring restriction relation '3904270' with unknown from-way.
Warning: Ignoring restriction relation '3904270' with unknown to-way.
Warning: No way found for reference '60333309' in relation '4507872'
Warning: Ignoring restriction relation '4507872' with unknown from-way.
Warning: No way found for reference '330460453' in relation '4666094'
Warning: No way found for reference '330460453' in relation '4666103'
Warning: Ignoring restriction relation '4806373' with unknown to-way.
done (194ms).
 Removed 211 traffic lights before loading plain-XML
 Import done:
   5499 nodes loaded.
   33 types loaded.
   8556 edges loaded.
Proj projection parameters used: '+proj=utm +zone=33 +ellps=WGS84 +datum=WGS84 +units=m +no_defs'.
Removing self-loops ... done (1ms).
Joining junction clusters ... 
Warning: Reducing junction cluster 1673585734,26701256,29192960,3590535061,3590535063,4590472038,5632884667 (5 incoming edges).
Warning: Reducing junction cluster 258485791,27411258,2796846632,30731464 (not compact (maxEdge=831659093#1 length=7.86)).
Warning: Not joining junctions 1668717163,258485805 (only 1 entry node).
Warning: Reducing junction cluster 1791264884,3837028178,3918855386,859002301,9828800519,9828800521,9830554037,9830554041,9830554091 (not compact (maxEdge=23809678#0 length=8.16)).
Warning: Not joining junctions 3513888373,866264912 (only 1 entry node).
Warning: Not joining junctions 2454091577,262482618 (only 1 entry node).
Warning: Not joining junctions 262482676,6460260300 (only 1 edge within and no cross-traffic).
Warning: Not joining junctions 27005148,3378459428 (only 1 edge within and no cross-traffic).
Warning: Reducing junction cluster 29221535,29221562,3730313048,9828580196,9828580198,9828580208,9830552392,9830552393 (5 incoming edges).
Warning: Reducing junction cluster 3513423870,3513423873,3513423879,3513423880,3513423881,3513423882 (parallel outgoing -310176513#6,54698846#0).
done (21ms).
 Joined 184 junction cluster(s).
Removing empty nodes and geometry nodes ... done (15ms).
   1102 nodes removed.
Moving network to origin ... done (54ms).
Computing turning directions ... 
Warning: Ambiguity in turnarounds computation at junction '1206481791'.
Warning: Ambiguity in turnarounds computation at junction '1206481808'.
Warning: Ambiguity in turnarounds computation at junction '3345447311'.
Warning: Ambiguity in turnarounds computation at junction '3937026590'.
Warning: Ambiguity in turnarounds computation at junction '7448585407'.
done (4ms).
Assigning nodes to traffic lights ... done (2ms).
Guessing and setting on-/off-ramps ... done (6ms).
Warning: Found sharp turn with radius 7.15 at the end of edge '-194167259#1'.
Warning: Found sharp turn with radius 8.79 at the start of edge '-194962375#2'.
Warning: Found sharp turn with radius 8.42 at the end of edge '-23129533#1'.
Warning: Found sharp turn with radius 8.20 at the start of edge '-409507435#2'.
Warning: Found sharp turn with radius 7.84 at the end of edge '-503140348#1'.
Warning: Found sharp turn with radius 8.22 at the start of edge '-52348720#0'.
Warning: Found sharp turn with radius 7.32 at the end of edge '-52348720#1'.
Warning: Found sharp turn with radius 6.63 at the start of edge '-59332212#0'.
Warning: Found sharp turn with radius 6.10 at the start of edge '100944802#2'.
Removing sharp turn with radius 8.03 at the end of edge '1053166657'.
Removing sharp turn with radius 4.73 at the start of edge '167140670#3'.
Removing sharp turn with radius 4.82 at the start of edge '195411594#3'.
Removing sharp turn with radius 4.29 at the start of edge '30123145#2'.
Warning: Found sharp turn with radius 8.22 at the end of edge '52348720#0'.
Sorting nodes' edges ... done (6ms).
Computing node shapes ... done (66ms).
Computing edge shapes ... done (37ms).
Computing node types ... 
Warning: Converting invalid rail_crossing to traffic_light at junction 'cluster_1832049011_9820547961'.
Warning: Converting invalid rail_crossing to traffic_light at junction 'cluster_2341815018_26871465_9068723928_9821581099'.
Warning: Converting invalid rail_crossing to traffic_light at junction 'cluster_25954548_9068699945'.
Warning: Converting invalid rail_crossing to traffic_light at junction 'cluster_29221576_9066609025_9828800554_9828800559'.
Warning: Converting invalid rail_crossing to traffic_light at junction 'cluster_3129452762_7769466023_9856051669'.
done (3ms).
Computing priorities ... done (4ms).
Computing approached edges ... done (4ms).
Guessing and setting roundabouts ... done (1ms).
Computing approaching lanes ... done (8ms).
Dividing of lanes on approached lanes ... done (7ms).
Processing turnarounds ... done (1ms).
Rechecking of lane endings ... 
Warning: Edge '189133035#0' is not connected to outgoing edges at junction 'cluster_1631354272_1862786410_1862786420_1862786421_1862786424_1862786436_1862786438_1862786464_1862786477_1862786478_1862786491_1862786497_21432798_29123438_29221602_595038812_6795798214_6795798215_6795798216_6795798217_6795798218_6795798219_6795798220_6795798221_6795798222_6795798223_7766315014'.
done (2ms).
Joining traffic light nodes ... done (3ms).
Computing traffic light control information ... 
Warning: The rail crossing '1662153923' does not have any roads.
Warning: The rail crossing '1711820647' does not have any roads.
Warning: The rail crossing '1862786416' does not have any roads.
Warning: The rail crossing '4402536776' does not have any roads.
Warning: The rail crossing '4567083492' does not have any roads.
done (1ms).
Computing node logics ... done (25ms).
Computing traffic light logics ... 
Warning: The traffic light '3204786098' does not control any links; it will not be build.
Warning: Could not build program '0' for traffic light '3204786098'
Warning: The traffic light '4591015618' does not control any links; it will not be build.
Warning: Could not build program '0' for traffic light '4591015618'
done (6ms).
 74 traffic light(s) computed.
Building inner edges ... 
Warning: Speed of turning connection '27080261_0->177195505#3_0' reduced by 24.90 due to turning radius of 1.51 (length=1.66, angle=168.28).
done (41ms).
Warning: The traffic light 'joinedS_6' cannot be adapted to a cycle time of 90.00.
Warning: The traffic light 'joinedS_6' has a high cycle time of 268.00.
Warning: The traffic light 'cluster_1631354272_1862786410_1862786420_1862786421_1862786424_1862786436_1862786438_1862786464_1862786477_1862786478_1862786491_1862786497_21432798_29123438_29221602_595038812_6795798214_6795798215_6795798216_6795798217_6795798218_6795798219_6795798220_6795798221_6795798222_6795798223_7766315014' cannot be adapted to a cycle time of 90.00.
Warning: The traffic light 'cluster_1631354272_1862786410_1862786420_1862786421_1862786424_1862786436_1862786438_1862786464_1862786477_1862786478_1862786491_1862786497_21432798_29123438_29221602_595038812_6795798214_6795798215_6795798216_6795798217_6795798218_6795798219_6795798220_6795798221_6795798222_6795798223_7766315014' has a high cycle time of 313.00.
-----------------------------------------------------
Summary:
 Node type statistics:
  Unregulated junctions       : 0
  Dead-end junctions          : 2396
  Priority junctions          : 1053
  Right-before-left junctions : 238
  Traffic light junctions      : 85
  Rail crossing junctions      : 63
  Rail signal junctions      : 29
 Network boundaries:
  Original boundary  : 13.37,52.50,13.45,52.54
  Applied offset     : -389610.86,-5819107.27
  Converted boundary : 0.00,0.00,3447.95,3343.01
-----------------------------------------------------
Writing network ... done (282ms).
Warning: 6 total messages of type: Ambiguity in turnarounds computation at junction '%'.
Warning: 18 total messages of type: Ambiguous railway kilometrage direction for way '%' (assuming forward)
Warning: 8 total messages of type: Converting invalid rail_crossing to traffic_light at junction '%'.
Warning: 22 total messages of type: Discarding unknown compound '%' in type '%' (first occurence for edge '%').
Warning: 6 total messages of type: Found sharp turn with radius % at the end of edge '%'.
Warning: 16 total messages of type: Found sharp turn with radius % at the start of edge '%'.
Warning: 178 total messages of type: No way found for reference '%' in relation '%'
Warning: 8 total messages of type: Not joining junctions % (%).
Warning: 55 total messages of type: The rail crossing '%' does not have any roads.
Success.
Written configuration to 'osm.polycfg'
Parsing network projection from 'osm.net.xml' ... done (0ms).
Parsing nodes from osm-file 'osm_bbox.osm.xml.gz' ... done (509ms).
Parsing relations from osm-file 'osm_bbox.osm.xml.gz' ... done (410ms).
Parsing edges from osm-file 'osm_bbox.osm.xml.gz' ... done (437ms).
Success.
Processing Cars
calling /usr/share/sumo/bin/duarouter -n /home/fanwu/work/ns3/ns3 old versions/VANET/VANET_sig/map/2022-07-17-16-58-29/osm.net.xml -r /home/fanwu/work/ns3/ns3 old versions/VANET/VANET_sig/map/2022-07-17-16-58-29/osm.passenger.trips.xml --ignore-errors --begin 0 --end 3600 --alternatives-output NUL --no-step-log --no-warnings -o /home/fanwu/work/ns3/ns3 old versions/VANET/VANET_sig/map/2022-07-17-16-58-29/osm.passenger.rou.xml
Success.
Traceback (most recent call last):
  File "/usr/share/sumo/tools/osmWebWizard.py", line 497, in build
    builder.build()
  File "/usr/share/sumo/tools/osmWebWizard.py", line 321, in build
    randomTrips.main(randomTrips.get_options(options))
  File "/usr/share/sumo/tools/randomTrips.py", line 761, in main
    sumolib.xml.insertOptionsHeader(options.routefile, options)
  File "/usr/share/sumo/tools/sumolib/xml.py", line 524, in insertOptionsHeader
    with fileinput.FileInput(filename, inplace=True) as fileToPatch:
AttributeError: FileInput instance has no attribute '__exit__'

Recovering
Recovering

I do not understand why.  
Also, I failed to use openstreetmap. Whatever map I use, there are at least 5 vehicles owning invalid routes. I cannot continue my experiments any more.

**Comment by namdre** [comment] 2022-07-17 09:42
version 1.14.0 (accidentally) broke python 2.7 support. Either use python3 or download the latest development version with restored support.

duplicate of #11159

**Closed by namdre** 2022-07-17 09:42 UTC
Labels: duplicate

**Comment by conjurer-Fan-Wu** [comment] 2022-07-17 14:23
YES, I used python3 and the process continued.
