### ISSUE TITLE
The traci tool can not get the num of vehichles passed the E3 detector during last step in simulation? 

### ISSUE THREAD

**Issue by lightly-lyx** [eclipse/sumo#8924] opened 2021-08-07 02:46 UTC
Can I use traci tool to get the num of vehichles passed the E3 detector during last step in simulation?

**Comment by namdre** [comment] 2021-08-09 06:41
Thats what traci.multientryexit.getLastStepVehicleNumber is for

**Comment by lightly-lyx** [comment] 2021-08-09 09:04
the output of E3 detector can provide "vehicleSum" to count **vehicles that have left the area during the interval**, but I can't get this atrribute by Traci.  (the "multientryexit. getLastStepVehicleNumber()" just provide the number of vehicles **within** the detector, and this is not what I want)

**Comment by namdre** [comment] 2021-08-09 11:21
- vehicles that left during the interval: currently, not possible (duplicate of ##2139)
- vehicles that left during the last step: only by storing the previous value of `getLastStepVehicleIDs` and and couning the number of vehicles that are no longer present compared to the current value of  `getLastStepVehicleIDs`. (Doing this repeatedly also gives you the aggregated value).

**Closed by namdre** 2021-08-09 11:21 UTC
Labels: question
