### ISSUE TITLE
Error message displayed on screen after ending simulation with Traas

### ISSUE THREAD

**Issue by grazmand** [eclipse/sumo#5188] opened 2019-02-13 14:17 UTC
When a simulation called from Traas Java script ends by means of the command conn.close(), where conn is an object of the class SumoTraciConnection, on the SumoGui appears the following error text message:

Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).

And then appears the following log error message window:

Simulation ended at time 10000.00
Reason: An error occured (see log).
Do you want to close all open files and views?

**Comment by namdre** [comment] 2019-02-13 14:41
duplicate of #4962 
While undesireable, this error is mostly cosmetic and should not affect generated results.

**Closed by namdre** 2019-02-13 14:41 UTC
Labels: duplicate
