### ISSUE TITLE
OpenDrive: export crossings as road objects

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#10432] opened 2022-03-29 00:32 UTC
Hello.

I am trying to convert sumo net to opendrive and link it with carla.

However, if sumo net is converted to opendrive using netconvert, there seems to be no information about crosswalks in the .xodr file.

I would like to know if there is a way to put the crosswalk in sumo net into .xodr.

thank you.
[sumo.net.zip](https://github.com/eclipse/sumo/files/8367137/sumo.net.zip)

=======================
I used the script below to convert sumo net to opendrive.
netconvert -s sumo.net.xml --opendrive-output od.xodr

**Comment by namdre** [comment] 2022-12-20 19:20
duplicate of #12229

**Comment by m-kro** [comment] 2023-05-08 07:59
Just that the crossing width is not exported correctly (roughly 1m in OpenDRIVE whereas SUMO uses an entire car lane width.

**Comment by namdre** [comment] 2023-05-08 09:10
the root cause for the invalid width is  #13203  (the 1m originates in a default object length of -1 since our exported crossings don't even set the length attribute)

**Comment by namdre** [comment] 2023-05-08 10:22
actually, there was a geometry bug in #12229 as well

**Closed** 2023-05-08 10:22 UTC
Labels: enhancement, a:netconvert, OpenDRIVE
