### ISSUE TITLE
Netedit shows changed status after loading additionals or demand elements

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#6946] opened 2020-04-27 14:27 UTC
When I load an additional or demand file, netedeit handles them as changed, and highlights the "Save additionals" or "Save demand elements" even I did not change anything.
If I click on "Save .." button it pops a window to select filename. It shall save the content under the name of the loaded file.

**Comment by namdre** [comment] 2020-12-02 10:56
duplicate of #5971

**Closed by namdre** 2020-12-02 10:56 UTC
Labels: a:netedit, bug, duplicate
