### ISSUE TITLE
not all vehicles entering second 'through' lane

### ISSUE THREAD

**Issue by johnnotraffic** [eclipse/sumo#9058] opened 2021-09-02 08:43 UTC
vehicles coming from east not entering second 'through' lane
![1](https://user-images.githubusercontent.com/89970271/131812148-c829ae15-be34-46e4-a7fa-76abf5fc4d75.png)

net.xml, sumocfg and other files:
[model.zip](https://github.com/eclipse/sumo/files/7097899/model.zip)

traci script:
[test_model.zip](https://github.com/eclipse/sumo/files/7098670/test_model.zip)

**Comment by namdre** [comment] 2021-09-02 09:22
can you attach the traffic definition and sumocfg?

**Comment by johnnotraffic** [comment] 2021-09-02 09:46
added sumocfg, routes and vtypes files

**Comment by namdre** [comment] 2021-09-02 11:24
There are no vehicles,flows or trips defined in your input. Are you adding the vehicles with traci?
If yes, include your traci script or a trace file of the commands (https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands)

**Comment by johnnotraffic** [comment] 2021-09-02 11:55
added traci script

**Comment by namdre** [comment] 2021-09-02 12:37
I'ts a strategic choice: the right lane (lane_14) only allows turning right after the junction. In order to continue their route without the need to change lane in dense traffic, vehicles prefer to remain on the left lane (lane_15).
The problem is easily fixed by letting the two straight-going lanes target the two straight going outbound lanes.

Note, that your network has lane ids that do not conform to the sumo standard naming convention of edges and lanes. this may lead to problems with sumo tools. See https://sumo.dlr.de/docs/FAQ.html#i_made_changes_to_the_netxml-file_but_it_did_not_work_as_expected_why

**Closed by namdre** 2021-09-02 12:37 UTC
Labels: question

**Comment by johnnotraffic** [comment] 2021-09-02 13:47
I tried to your solution but the vehicles keep stopping mostly in the left lane
![2](https://user-images.githubusercontent.com/89970271/131854925-de752ca3-2142-4f43-9f2c-460ade35be53.png)

updated model:
[model.net.zip](https://github.com/eclipse/sumo/files/7099291/model.net.zip)

**Comment by namdre** [comment] 2021-09-02 14:26
fixed connections in dark blue

![Screenshot from 2021-09-02 16-25-56](https://user-images.githubusercontent.com/6240630/131861635-da113729-3797-4c13-9cd5-cbcae3142dca.png)

**Comment by johnnotraffic** [comment] 2021-09-02 18:47
Oh! thank you!
