### ISSUE TITLE
Conversion from SUMO.net.xml to OpenDrive connections issue 

### ISSUE THREAD

**Issue by gregor-ovsenjak** [eclipse/sumo#9796] opened 2021-12-15 10:57 UTC
Hello, I am quite new to SUMO. I am using the SUMO netconvert tool to convert some OSM road networks
to SUMO net.xml to OpenDrive format. However when trying to run the ODR file in ESMINI, there seems to be a problem with the connection of lanes. This issue  always happens when the number of lanes changes (from 2 lanes to 3 lanes) and is always present at junctions. It is hard to describe the problem so I copied an example of issue from the ODR file. 

  
---

        </connection>**SUMO-version:**

![Screenshot 2021-12-15 115330](https://user-images.githubusercontent.com/61007370/146174044-0e114518-e9d5-41d4-9fdc-be0226653202.png)

![Screenshot 2021-12-15 115309](https://user-images.githubusercontent.com/61007370/146174069-f97fc95f-f8ae-4c43-9f3b-27a28eeb34ea.png)

![144](https://user-images.githubusercontent.com/61007370/146174080-74a61bb5-009b-4630-ab1c-6d76a9c7a77c.png)

Windows 10 operating system
```
<road name="Münzgrabenstraße" length="24.83257365" id="145" junction="-1">
        <link>
            <predecessor elementType="junction" elementId="8"/>
            <successor elementType="junction" elementId="6"/>
        </link>
<road name=":1377471295_0" length="8.17676380" id="168" junction="6">
            <link>
                <predecessor elementType="road" elementId="145" contactPoint="end"/>
                <successor elementType="road" elementId="144" contactPoint="start"/>
            </link>

<junction name="1377471295" id="6">
        <connection id="0" incomingRoad="145" connectingRoad="168" contactPoint="start">
            <laneLink from="-1" to="-2"/>
        </connection>
        <connection id="1" incomingRoad="145" connectingRoad="169" contactPoint="start">
            <laneLink from="-1" to="-1"/>
        </connection>
        <connection id="2" incomingRoad="153" connectingRoad="170" contactPoint="start">
            <laneLink from="-1" to="-2"/>
        </connection>
        <connection id="3" incomingRoad="153" connectingRoad="171" contactPoint="start">
            <laneLink from="-1" to="-1"/>
```

When I manually fix the error :  When I change the code : `<laneLink from="-1" to="-2"/>` to  `<laneLink from="-1" to="-1"/> `the ODR can run in ESMINI. 
#9637

**Comment by namdre** [comment] 2021-12-15 11:42
It sounds as if your are describing a duplicate of #9637 which as been fixed in dev.
Please try converting your network with the latest development version instead of the latest release (1.11.0)
https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version

**Comment by gregor-ovsenjak** [comment] 2021-12-15 11:49
Thank You, I did that and now it works correctly.

Thank You for Your help.

**Closed** 2021-12-15 14:42 UTC
Labels: question
