### ISSUE TITLE
convert from xodr map has broken connections

### ISSUE THREAD

**Issue by sapirbm** [eclipse/sumo#6824] opened 2020-03-19 19:09 UTC
hello,
we use xodr maps and converting them using netconvert. we have a new map that has some broken connections, the connection exist in xodr but is missing from the net.xml file.
the conversion is not that special:
 --output.original-names true
 --opendrive.import-all-lanes true
 --offset.x 0
 --offset.y 0
 --precision 8
 --no-warnings true

i have attached the specific part that fails to connect on net.xml.
thanks in advance for the help.
Sapir.

[cut_map.zip](https://github.com/eclipse/sumo/files/4356502/cut_map.zip)

**Comment by namdre** [comment] 2020-03-19 21:42
duplicate of #6712 (use https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version)

**Closed by namdre** 2020-03-19 21:42 UTC
Labels: duplicate
