### ISSUE TITLE
sumo-gui does not automatically refresh its windows anymore

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#9037] opened 2021-08-30 12:24 UTC
I compiled and ran the newest sumo-gui github-version on my Windows machine and all parts of the gui are not refreshing automatically. Vehicle shapes only refresh when I zoom in/out, time only refreshes when I click on it, etc.

The SUMO versions 1.8 (+added code) and the official 1.9 still work correctly.

**Comment by namdre** [comment] 2021-08-30 13:05
probably regression from #6371

**Comment by namdre** [comment] 2021-08-30 14:32
@Domsall can you check if the problem is fixed on your end? I wasn't able to reproduce it after my fix. (Before, I was able to trigger the effect by setting breakpoints).

**Comment by namdre** [comment] 2021-08-30 14:33
note: regression label only needs to remain for things that were part of a release.

**Comment by Domsall** [comment] 2021-08-30 15:04
It works again.
There is still one difference: When opening sumo-gui and starting the simulation with a configuration file and `<start value="1"/>`, the gui does not refresh until I stop the simulation once. When I start a simulation a second time in the same window it refreshes straight away.

**Comment by namdre** [comment] 2021-08-30 19:55
I'm unable to reproduce this yet.
- Is the simulation running for a significant time without screen updates? 
- Is TraCI involved? 
- Does the scenario have to be very big or very small?

**Comment by Domsall** [comment] 2021-08-31 10:50
It tested the behavior with 3 different scenarios and all behave the same.

- the simulation runs without screen updates until I stop the simulation via gui for the first time or a warning is thrown.
- I only open sumo-gui and open the configuration file via "open simulation", no traci

**Comment by namdre** [comment] 2021-08-31 12:45
I'm still unable to reproduce this. Can you send me a small scenario?
Can you also trigger the issue when running `sumo-gui -c whatever.sumocfg` or only when opening the sumocfg from the gui itself? (both are working for me)

**Comment by Domsall** [comment] 2021-09-01 09:30
Yes I can also trigger it via command line.

A small scenario:
[circles_collisions_EIDM_and_platform_dependancy.zip](https://github.com/eclipse/sumo/files/7089944/circles_collisions_EIDM_and_platform_dependancy.zip)

a short video:
https://user-images.githubusercontent.com/53042793/131647873-5bf02069-afe4-4920-bb9b-d4b47bcdc43f.mp4

**Comment by namdre** [comment] 2021-09-01 10:05
Unfortunately, I still cannot reproduce this.

- can you reproduce the issue with the debug build?
- if so, can you apply the following patch and send me the command line output when running this scenario with the patched debug version? (note: the release build requires an extra compile flag to enable command line output on windows)


```
diff --git a/src/gui/GUIApplicationWindow.cpp b/src/gui/GUIApplicationWindow.cpp
index d58584bad08..118930387a3 100644
--- a/src/gui/GUIApplicationWindow.cpp
+++ b/src/gui/GUIApplicationWindow.cpp
@@ -1606,6 +1606,7 @@ GUIApplicationWindow::handleEvent_SimulationStep(GUIEvent*) {
     // only skip if the simulation is running
     if (t - myLastStepEventMillis < 20 && myRunThread->simulationIsStopable()) {
         // do not try to redraw with more than 50FPS (#6371)
+        std::cout << SIMTIME << " skipDraw t=" << t << " lastDraw=" << myLastStepEventMillis << " delta=" << t - myLastStepEventMillis << "\n";
         return;
     }
     myLastStepEventMillis = t;
```

**Comment by Domsall** [comment] 2021-09-01 10:49
jup is also happens in the debug mode.

I ran the simulation with the output and stopped it once at approx. 2806s. After that the window was refreshing normal.

[Window_output.txt](https://github.com/eclipse/sumo/files/7090442/Window_output.txt)

**Comment by namdre** [comment] 2021-09-01 11:24
for some reason the clock returned negative values on your system and this was triggering the problem.

**Closed** 2021-09-01 11:23 UTC
Labels: a:sumo-gui, bug
