### ISSUE TITLE
allow inspecting the stops of a vehicle (trac #2646)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2646] opened 2016-11-04 09:18 UTC
At least the upcoming stops should be shown (lane,pos or stopID) and duration/trigger parameters

nice-to-have
* seeing the past stops would be nice
* dynamically deleting stops

Migrated from http://sumo.dlr.de/ticket/2646
```json
{
    "status": "new", 
    "changetime": "2016-11-04T09:18:40Z", 
    "description": "At least the upcoming stops should be shown (lane,pos or stopID) and duration/trigger parameters\n\nnice-to-have\n* seeing the past stops would be nice\n* dynamically deleting stops", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1478251120166607", 
    "component": "simulation gui (GUISIM)", 
    "summary": "allow inspecting the stops of a vehicle", 
    "priority": "major", 
    "keywords": "", 
    "time": "2016-11-04T09:18:40Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by namdre** [comment] 2018-07-23 19:49
current and upcoming stops are shown (duplicate of #3679)

**Closed by namdre** 2018-07-23 19:49 UTC
Labels: a:SUMO-GUI, enhancement
