### ISSUE TITLE
Shapefile import error: `Warning: Invalid latitude 116.45`

### ISSUE THREAD

**Issue by HanwGeek** [eclipse/sumo#7787] opened 2020-11-13 11:32 UTC
I use `netconvert` to import a shapefile like this:
```bash
netconvert --shapefile-prefix ./data/clip \
    --shapefile.street-id id \
    --shapefile.from-id SOURCE \
    --shapefile.to-id TARGET \
    --shapefile.use-defaults-on-failure
```
But it tells me that
```bash
Warning: Invalid latitude 116.45
Warning: Invalid latitude 116.45
Warning: Invalid latitude 116.45
...
```
However, the shapefile shows correctly in `QGIS` and `GeoPandas`. It seems that the `netconvert` mixed the longtitude and the latitude. What can I do to modify the field?

**Comment by namdre** [comment] 2020-11-13 12:04
use option --shapefile.traditional-axis-mapping

duplicate of #6936

**Closed by namdre** 2020-11-13 12:04 UTC
Labels: duplicate, question
