### ISSUE TITLE
SUMO Website Certificate Invalid

### ISSUE THREAD

**Issue by abrac** [eclipse/sumo#11910] opened 2022-10-28 07:26 UTC
Hi there. The SSL certificate of https://sumo.dlr.de has expired, so we can no longer access the documentation.

**Comment by boxjuke** [comment] 2022-10-28 08:08
Hi. I am also struggling with the same issue that SSL certificate of SUMO documentation and other services has expired. I can not access SUMO documentation. Please let me know how to figure it out. It seems the problem is not an individual-level problem.

**Comment by namdre** [comment] 2022-10-28 08:23
Thanks for the notice. We are aware of the problem and working on a fix.

**Comment by namdre** [comment] 2022-10-28 10:04
should be fixed now

**Closed by namdre** 2022-10-28 10:04 UTC
Labels: c:doc, p:important
